### ISSUE TITLE
表單區(3) 用手機打開，表格看起來會很長

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#101]
[表單區](3) 用手機打開，表格看起來會很長
在想要不要特別針對手機調整版型?

**Comment by qcl** [comment]
我覺得如果可以善用 grid system 的 css 就盡量不要寫特例 :p

**Comment by mark86092** [comment]
我目前看到的是表單區的等級只設定到 `col-sm` 看起來還有更多 grid 可調

**Comment by barry800414** [comment]
噢，我的意思就是用grid system去調版型
目前看起來真的蠻長的
