### ISSUE TITLE
主視覺(1) 的背景圖片在手機上需要全背景

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#103]
這個是套件設計者設計的，不確定修過是否比較好

See #102

**Comment by qcl** [comment]
我會覺得螢幕太小的時候適當露出下方也是一種暗示下面有東西的方法，全螢幕的話就只剩下那些action可以引導了？

**Comment by mark86092** [comment]
是的，所以我很好奇作者設計的時候是不是有考慮這個

而且長圖片其實不好找圖

**Comment by qcl** [comment]
我猜他應該是要保留原圖比例吧，我會傾向於不修改這個部分

**Comment by barry800414** [comment]
ok, 如果其他人有反應再討論
