### ISSUE TITLE
介紹區(2) 表格區(3) Landing Page 使用流程修正的問題

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#115]
登入之後，在介紹區(2)的地方就不需要有登入功能
在表格區(3)也不用跳出modal

**Comment by mark86092** [comment]
其實表格區有檢查，如果有登入，就不需要"再登入"，也不會跳modal

**Comment by mark86092** [comment]
Here: https://github.com/goodjoblife/WorkTimeSurvey/pull/111/files#diff-42f69825340f0b5fa628d80900a46daaR48

**Comment by barry800414** [comment]
ok, then I close the issue
