### ISSUE TITLE
表單區(3) help-text偏左 & "工作日表訂工時"跑版

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#116]
![image](https://cloud.githubusercontent.com/assets/3805975/16639719/cc5df120-4424-11e6-96f1-2e7516d7ee58.png)

help-text感覺置中比較好

**Comment by mark86092** [comment]
手機上面，會變成多行文字 置中 的情況，如果剛好一兩個字結尾，超怪的

**Comment by barry800414** [comment]
有圖可以看嗎?

**Comment by mark86092** [comment]
![image](https://cloud.githubusercontent.com/assets/1908007/16640778/8c999f7c-442d-11e6-84a9-95716110316b.png)

模擬圖

**Comment by barry800414** [comment]
我覺得大螢幕偏左還是很奇怪，看能不能「我有疑問」這四個字要換行一起換行

**Comment by barry800414** [comment]
「我有疑問」這四個字已經加上 word-break: keep-all 的class。不會一個字斷行了

**Comment by qcl** [comment]
我覺得在大螢幕上可以對在 input box 的左緣？

**Comment by mark86092** [comment]
我覺的可耶，透過 grid 操作縮排

**Comment by barry800414** [comment]
只有我覺得字偏左蠻怪的嗎@_@

**Comment by barry800414** [comment]
那這樣，我想先把工作日表訂工時 不要換行，ok嗎?
