### ISSUE TITLE
Duplicate company name

### ISSUE THREAD

**Issue by qcl** [goodjoblife/WorkTimeSurvey#127]
![2016-07-06 11 27 05](https://cloud.githubusercontent.com/assets/485496/16624368/f5a292b2-43d3-11e6-9fc8-2f5fb4c659fb.png)

**Comment by mark86092** [comment]
They all share the same name... QQ https://tranquil-fortress-92731.herokuapp.com/companies/search?key=%E8%81%AF%E7%99%BC

**Comment by qcl** [comment]
What the... XDDDDDDD

**Comment by barry800414** [comment]
一堆商業登記的名字一樣...
目前的排序方法是什麼~~ 
有可能排序的時候公司優先嗎?    (公司先插入id比較前面?

**Comment by mark86092** [comment]
我是可以按造 type (公司，商業排序) 然後 統編

如何？

**Comment by barry800414** [comment]
可以的!   希望有稍微解決問題

**Comment by barry800414** [comment]
我剛想到另一種方式，但不曉得會不會太麻煩。
排序: 公司 -> 公司規模 -> 統編

**Comment by mark86092** [comment]
那要看怎麼定義 "公司規模"

**Comment by barry800414** [comment]
阿..原本以為公司資料會有公司規模 (會有個 人數範圍)
不過可以考慮用資本額? 
我來看一下data

**Comment by barry800414** [comment]
剛剛測試了一下資料，所有的「公司」都會有「資本額(元)」這個欄位。  把字串裡面的逗號移除掉後，都可以轉成數值。

修正: 准許設立的財都有資本額欄位

**Comment by mark86092** [comment]
I'll try to renew the data, hoping the 500MB size is enough

**Comment by mark86092** [comment]
所以要用 `資本額` 當排序之一嘛？

**Comment by barry800414** [comment]
我自己覺得make sense，大的排前面

**Comment by barry800414** [comment]
去除掉沒有「公司名稱」、「公司狀況」的，以及大陸公司
公司狀況是「核准認許」或「核准設立」的，有「在中華民國境內營運資金」、「資本總額(元)」其中一個欄位

**Comment by mark86092** [comment]
目前已經用資本額作為基本的排序原則，先 close，有問題在打開追蹤
