### ISSUE TITLE
Navbar 在平板螢幕上太長，會分兩行

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#130]
![default](https://cloud.githubusercontent.com/assets/3805975/16640583/b572bc00-442b-11e6-862f-faa6de273905.png)

**Comment by mark86092** [comment]
我覺的這樣還ok 說

**Comment by qcl** [comment]
不然就把字變得精簡一點，像是「工時透明化運動」、「參與」、「問答」之類的XD

**Comment by barry800414** [comment]
感覺可以。我剛想到另一種，把聯絡我們拔掉。
要聯絡我們應該會去看關於我們?

**Comment by qcl** [comment]
那我就把「聯絡我們」從 Navigation bar 拿掉好了 :p

**Comment by barry800414** [comment]
ok! thx!

**Comment by qcl** [comment]
我從三個頁面上都拿掉？

**Comment by barry800414** [comment]
yes, please 
事實上show.html忘記放了XD
