### ISSUE TITLE
表格區(3) 表格是否太長，考慮先隱藏讓使用者點開填更多?

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#133]

**Comment by qcl** [comment]
這邊的問題其實是要定義想要的資料什麼是：
- Must have
- Nice to have

**Comment by barry800414** [comment]
我這邊的想法是，從使用者的角度出發
「實際平均工時」、「加班頻率」是Must have
「表訂工時」、「最近一週工時」是Nice to have

但是因為現在呈現資料上，是以最近一週工時為主，我擔心會影響太多東西。

**Comment by mark86092** [comment]
如果有必要欄位變更，後端也要修，筆記一下

**Comment by barry800414** [comment]
目前看起來沒有要改，先關掉
