### ISSUE TITLE
搜尋的按鈕跑掉 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#134]
![default](https://cloud.githubusercontent.com/assets/3805975/16641229/161db1ea-4431-11e6-82fc-4e392bc28041.png)

之前我改的這兩個commit 惹的禍
https://github.com/goodjoblife/WorkTimeSurvey/commit/df0378c04a3d50a82418e1cd0c868b8b217e9407
https://github.com/goodjoblife/WorkTimeSurvey/commit/77a270dbeea32560f488b320dcfd19989a903e25

**Comment by mark86092** [comment]
跟 df0378c 有關

**Comment by mark86092** [comment]
跟 77a270d 應該沒關係

**Comment by barry800414** [comment]
其實有的~  我兩個是連動在改的，它會影響social button在小螢幕上的外觀。
總之我會看怎麼fix

**Comment by mark86092** [comment]
![image](https://cloud.githubusercontent.com/assets/1908007/16643873/07fa8560-444b-11e6-8b4a-2d9899127832.png)

這個相關的也需要解決

**Comment by barry800414** [comment]
![default](https://cloud.githubusercontent.com/assets/3805975/16680557/f9e4df16-4521-11e6-863f-98923b062646.png)
看起來還是歪掉的，reopen this issue

**Comment by qcl** [comment]
這個我來調看看好了

**Comment by barry800414** [comment]
看起來沒有問題了，應該是我剛剛沒有更新到
