### ISSUE TITLE
搜尋按鈕與表格太靠近

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#135]
![default](https://cloud.githubusercontent.com/assets/3805975/16641285/a9cdf3dc-4431-11e6-9bd3-ffd3733f10f7.png)

**Comment by mark86092** [comment]
`.btn-default {margin-top: 10px}` 這個是造成按鈕跑掉的主因

input-group 是按鈕跟 input 黏在一起的原因
