### ISSUE TITLE
公司/單位名稱 或 統一編號的地方可能要強調一下「或」

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#138]
使用者第一個問題，是兩個都要填嗎?
公司/單位名稱 或 統一編號的地方可能要強調一下「或」?
或是想辦法讓人一看就注意到

![default](https://cloud.githubusercontent.com/assets/3805975/16643734/f440bb1c-4449-11e6-83fb-ada409af914a.png)

**Comment by qcl** [comment]
這邊我之前覺得理想的方式可能是只有一個 input box 然後輸入統編可以自動補完公司名稱？因為兩個 input box 擺在同一個 row 裡面在小螢幕的狀況下就是都太小，有點分散焦點跟輸入會有影響

**Comment by barry800414** [comment]
目前是反過來，輸入公司名稱會自動補完統編
哪一種比較Make sense?

**Comment by mark86092** [comment]
兩個願望一次滿足？一個 input，一個 Label

輸入統編，就查出公司，顯示在 Label

如果輸入公司，input 要有能力做 autocomplete，然後最後 Label 有 統編與公司名稱

這兩個應該不會衝突：統編是數字，當輸入數字達到共8位時，就可以假設是統編來查詢公司，其他情況都可以當作是公司名稱

**Comment by mark86092** [comment]
我可以來做一個 demo 的 input 來看

**Comment by barry800414** [comment]
如果可以自動辨識的話是最好的，比較擔心技術上有困難
確定統編都是八碼的話，應該會好做很多

**Comment by mark86092** [comment]
我突然想到，後端現在是：

有 `company_id` --> 自動查出 `company_name`
只有 `company_name` --> 反查出合適的 `company_id`

我在想，能不能有一個格子讓使用隨意輸入 id 或 名稱，我們的 ajax 都會自動幫它 autocomplete 成 company_id
