### ISSUE TITLE
感謝及分享區，在還沒上傳前先顯示一個分享鈕?

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#140]
感謝及分享區，在還沒上傳前先顯示一個分享鈕?
如果使用者不想上傳，先往下滑，至少可以看到分享鈕

**Comment by mark86092** [comment]
只有上傳成功才會顯示整個section，可能要檢查一下流程

**Comment by barry800414** [comment]
想說簡單的解決方案是把原本的result section拆成一個share section & result section
share section 只有分享的按鈕
result section 是最新N筆資料的table

**Comment by barry800414** [comment]
這個有沒有結論?
