### ISSUE TITLE
Tweak about us page's style

### ISSUE THREAD

**Issue by qcl** [goodjoblife/WorkTimeSurvey#145]

**Comment by qcl** [comment]
![2016-07-08 5 15 21](https://cloud.githubusercontent.com/assets/485496/16682944/b89e397c-452f-11e6-832e-4a61fd601c52.png)
![2016-07-08 5 15 31](https://cloud.githubusercontent.com/assets/485496/16682949/bef7f5ec-452f-11e6-90ad-da75972bfcd3.png)

**Comment by barry800414** [comment]
拍謝其實我沒有懂Tweak的意思@@

**Comment by mark86092** [comment]
看起來是把 清單修好，和標題層級正確

**Comment by qcl** [comment]
Tweak 是微調的意思 :p
