### ISSUE TITLE
Need Facebook App Icon

### ISSUE THREAD

**Issue by qcl** [goodjoblife/WorkTimeSurvey#150]
Need a icon for Facebook App, to replace the default one.
![2016-07-08 9 58 07](https://cloud.githubusercontent.com/assets/485496/16689766/22126db6-4557-11e6-971a-e7f7ec5e7595.png)

**Comment by qcl** [comment]
It should be a 1024 x 1024 image

**Comment by barry800414** [comment]
@qcl  你覺得要顯示工時透明化運動還是 GoodJob好

**Comment by qcl** [comment]
@barry800414  我覺得 GJ 比較好，因為這個框框沒有很大，塞中文字的閱讀比較不易

**Comment by barry800414** [comment]
原來我弄1024 x 1024它還是那麼小...

**Comment by barry800414** [comment]
![fb_app_1024-1024](https://cloud.githubusercontent.com/assets/3805975/16692140/12e3b984-4562-11e6-97a9-e7bb9ab63f0b.png)
先用這個擋一下，等Mila回來請她設計logo

**Comment by qcl** [comment]
FB App use this as app icon temporally, so I close this issue.
