### ISSUE TITLE
關於我們的頁面，「加入我們」的部分文字修改

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#158]
改成 若您有以下任一專長，歡迎您 加入我們！link: (以FB聯絡我們)

**Comment by mark86092** [comment]
改成 `若您有以下任一專長，歡迎您 [加入我們 (FB)](link)` 呢？

想法主要是，加入我們是一個 action，所以有連結比較自然

**Comment by barry800414** [comment]
我是想說可以清楚一點說是以FB聯絡我們
