### ISSUE TITLE
表格區(3) 表格的文字考慮調開一點

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#159]
表格區(3) 表格的文字考慮調開一點，看起來比較不會那麼擠

**Comment by mark86092** [comment]
是指上下間距、左右間距，還是 label 與 input 間？
有點抽象

**Comment by qcl** [comment]
我猜是指上下間距可能可以拉開？

**Comment by mark86092** [comment]
我覺得這樣能不能分群，一群一群拉開間距？

**Comment by qcl** [comment]
from-group 調一下？

**Comment by qcl** [comment]
![2016-07-10 9 41 01](https://cloud.githubusercontent.com/assets/485496/16713884/0b1bce5e-46e7-11e6-933c-d42dc48ac969.png)

**Comment by mark86092** [comment]
我覺得看起來很OK

**Comment by barry800414** [comment]
是上下間距 by 施亭屹的opinion
