### ISSUE TITLE
介紹區(2) 是否分兩頁或用其他方式讓閱讀更順利

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#162]
這幾天我請幾個朋友適用，多數看到一堆字都直接往下滑。我認為那麼多字塞在一頁在手機板真的沒好處，要考慮分頁或用其他方法更易讀。

**Comment by qcl** [comment]
我比較好奇的是在相同的資訊量下分兩頁會比較願意閱讀嗎？@@

**Comment by barry800414** [comment]
我覺得會耶，像ppt你一頁塞一堆句子，跟兩頁相對少的句子，感覺是不同的

**Comment by qcl** [comment]
Update 一下目前的解法是先幫畫重點，所以問題變成
- 哪些是重點
- 重點的顏色？字重？

**Comment by barry800414** [comment]
用`<strong>` 就可以了吧?  我覺得不用那麼複雜
重點的字大家如果沒意見我就直接改了

**Comment by mark86092** [comment]
用 `<em>` 比較符合 html 設計原則，"強調" 的意思

**Comment by barry800414** [comment]
`<em>`在這個模板預設是斜體，`<strong>`比較適合
