### ISSUE TITLE
想辦法強調「匿名」這件事

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#163]
這幾天找幾個朋友測試，多數使用者第一個問題，這個是匿名的嗎?
我認為要更清楚一些。

**Comment by qcl** [comment]
我自己會覺得用 Facebook sign-in 會大幅度的削減對匿名的信心，這個是我個人的想法啦。

**Comment by mark86092** [comment]
以匿名信心來說，我覺的開放非 fb 送表單也是可以

**Comment by barry800414** [comment]
但是風險是可以大量洗資訊，我認為這樣的後果更糟，我寧願大家更認真看待上傳資訊這件事。
除非有辦法防堵這件事，那資料就可以標兩種，有登入的和沒有登入，有登入的信用比較高

**Comment by mark86092** [comment]
關於大量洗資訊，使用 reCaptcha (https://www.google.com/recaptcha/intro/index.html) 來做處理，大家有聽過嗎？不知道這樣會不會提高接受度？

**Comment by qcl** [comment]
有聽過，這蠻常見的，也是可以接受

**Comment by mark86092** [comment]
想丟到FB問問大家意見

**Comment by barry800414** [comment]
我原本拋出來不是考慮FB的問題，是幾乎沒有提到匿名這件事。
目前要改成怎樣還不確定，但我會先改文字的部份。
例如: 匿名參與工時透明化運動
