### ISSUE TITLE
表格區(3) 表情符號無法正常顯示

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#172]
![default](https://cloud.githubusercontent.com/assets/3805975/16722184/862b12cc-4777-11e6-9873-074d509c8687.png)

環境: windows 7 + chrome

**Comment by mark86092** [comment]
目前看起來是win的用戶有受影響，android, mac, ios, linux 都正常

需要 win 用戶看一下 http://getemoji.com/ 看看哪些字元 ok 的？

**Comment by mark86092** [comment]
可以的話，測試一下 ie

**Comment by barry800414** [comment]
Chrome:
![image](https://cloud.githubusercontent.com/assets/3805975/16723099/90ad45ca-477d-11e6-8753-8ac60119c65b.png)

IE:
![image](https://cloud.githubusercontent.com/assets/3805975/16723141/bee2c1ea-477d-11e6-9cbb-e8d504f636a6.png)

**Comment by mark86092** [comment]
這....QQ 不知道有沒有 open source 的圖可用

**Comment by barry800414** [comment]
我想問一下，我們現在的做法，是bootstrap在支援還是瀏覽器在支援的?

**Comment by mark86092** [comment]
都不是，emoji 是 unicode 字元集。在 win 上面，如果沒有對應的字形看的到，就沒辦法

**Comment by barry800414** [comment]
要用的話是不是就是找圖了?

**Comment by mark86092** [comment]
是的，我覺的找圖比較好處理

**Comment by barry800414** [comment]
http://emojione.com/
CC-BY 4.0
how about this?

**Comment by mark86092** [comment]
I think it is OK
