### ISSUE TITLE
navigation bar重新設計

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#182]
使用者回饋，他認為navbar通常長:
左上是漢堡    中間是產牌或產品名稱   右邊是個搜尋欄(放大鏡)

**Comment by qcl** [comment]
navigation bar 常見的種類其實不只有這一種，漢堡在左右的爭論（？）也不是一天兩天的了XD

主要其實就是一致性的行為。

**Comment by mark86092** [comment]
調查了一下：
- bootstrap 右漢堡，由上往下拉
- material design 左漢堡，有左往右拉
- github 左漢堡，由上往下拉

**Comment by barry800414** [comment]
之後前端會整個重新設計。 close it.
