### ISSUE TITLE
FB 應用程式登入頁

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#185]
![image](https://cloud.githubusercontent.com/assets/1908007/16736816/35f16460-47c1-11e6-81aa-2b68f22b5848.png)

連結當中的 GoodJob 會連到

https://www.facebook.com/games/?app_id=1750216878594984

看起來沒有東西，應該要修正

**Comment by barry800414** [comment]
彥齊我試不出你的視窗

**Comment by mark86092** [comment]
你是用什麼方法試不出來？

**Comment by barry800414** [comment]
![default](https://cloud.githubusercontent.com/assets/3805975/16768497/2fd513ae-4877-11e6-88e2-3558c67f645f.png)

點下去後:
![image](https://cloud.githubusercontent.com/assets/3805975/16768502/31227102-4877-11e6-87f9-a91173c6434f.png)

**Comment by barry800414** [comment]
是因為還沒publish嗎?
我不太確定原因是什麼

![image](https://cloud.githubusercontent.com/assets/3805975/16768881/c16bed0a-4878-11e6-9a34-853f257ef441.png)

這邊網址、網域都有放

**Comment by mark86092** [comment]
我也尋找答案中
