### ISSUE TITLE
上線前測試 & 系統設定

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#186]
系統測試:  
1. 先登出Facebook、並刪除自己帳戶允許的App權限
2. 以下測試時至少在電腦螢幕(iOs、Windows)、平版螢幕、手機螢幕(iOs, android)下測試
- [ ] 測試Key visual section，包含畫面縮小是否有問題、按鈕按下去是否向下拉
- [ ] 測試About section，包含Facebook Login、help-text
- [ ] 測試表格填入
  - [ ] 公司、職稱autocomplete的功能
  - [ ] 每個欄位檢查錯誤的功能
  - [ ] 上傳功能
  - [ ] 測試是否只能上傳 5 次
- [ ] 測試感謝及分享頁
- [ ] 測試聯絡我們的連結
- [ ] 測試使用者條款
- [ ] 測試 navigation bar
- [ ] 測試關於我們頁面
- [ ] 測試查看工時頁面
  - [ ] 上一頁下一頁功能
  - [ ] 搜尋功能

系統:
- [x] 重置database，將人工輸入的資料移除
- [x] Facebook App 發布  (讓非測試人員也可以用)
- [x] GA 埋設

**Comment by mark86092** [comment]
We are online, yeah ~
