### ISSUE TITLE
表格的字體太小

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#187]
我想問一下，我當初只有把工作日表訂工時的字稍為變小，因為它會換行
但是現在我看是全部都變小，我想問是哪一個commit 改的??
我是認為現在字有點太小耶

還是是我的錯覺?

**Comment by barry800414** [comment]
我想說 大於767 字改16px  
小於767 維持14px

**Comment by mark86092** [comment]
看紀錄是字沒變，有變得是 label 的 padding 變成 5px，所以看起來不會那麼擠

**Comment by barry800414** [comment]
瞭解!  可能是變寬之後覺得字有點小，我想說調大一點

**Comment by barry800414** [comment]
Done by #196
