### ISSUE TITLE
section顏色區隔嘗試

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#188]
![image](https://cloud.githubusercontent.com/assets/3805975/16753332/92416d0a-481b-11e6-810e-dd64ce98c502.png)

這樣會很奇怪嗎?

**Comment by barry800414** [comment]
![image](https://cloud.githubusercontent.com/assets/3805975/16760023/7ebf9654-484c-11e6-837f-a2abbb976509.png)
另一個，這個好像好一點

**Comment by mark86092** [comment]
I have no idea QQ

**Comment by barry800414** [comment]
目前規劃是這樣
kv: 有黃色背景
about: 白底
form: 黃色背景 (透明度0.3)
share/ result : 白底
qa: 黃色背景 (透明度0.3)
contact: 白底  

所以有 #190 #191 #189
