### ISSUE TITLE
畫面只有手機大小的時候，文字會被拉成一直排

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#19]
畫面只有手機大小的時候，文字會被拉成一直排

**Comment by mark86092** [comment]
![image](https://cloud.githubusercontent.com/assets/1908007/16457273/71e8d476-3e4d-11e6-9a79-3ba0be2f1bbd.png)
這個嘛？

**Comment by barry800414** [comment]
我發現會有那個問題的原因是我自己修改了CSS，先關掉這個issue
