### ISSUE TITLE
模糊搜尋的功能

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#228]
這個是Denny (求職天眼通開發者) & 其他使用者提的，之後接求職天眼通會需要用到。
在查詢工時的頁面，公司&職稱需要有模糊搜尋的功能，因為基本上使用者還是會亂打，名稱要完全一樣的話，不容易Match。

**Comment by eecarnegie** [comment]
請問搜尋公司功能是否還沒開放？我搜尋任何公司的關鍵字都無法找到任何結果，謝謝
https://worktime.goodjob.life/show.html

**Comment by mark86092** [comment]
@eecarnegie 是的，還沒開放。我們即將會在 #230 處理，屆時也會在粉專上通知

**Comment by barry800414** [comment]
目前是以職稱去搜尋工時資訊，但是必須是精確職缺比對，還沒有模糊搜尋!
如果一直無法搜尋到結果，可以考慮複製下面最新工時的職稱來尋找看看

**Comment by ensky** [comment]
@barry800414 @mark86092 職稱模糊搜尋有考慮用 nodejieba 做 full-text-search 嗎？
我試做了一個版本，你們可以參考看看
https://github.com/ensky/WorkTimeSurvey-backend/commit/92b752cf045ff5d733d51cda0d653828c7ce4080

如果你們不介意這樣實做的話，之後就差補上 test 跟跑 migration 將舊的資料補上 index 了。

現在 database 好像沒有 schema versioning?
這樣要加上 migration 似乎有一點麻煩。

另外，公司模糊搜尋我看你們好像是用 RegExp 去實做，不知道會不會太 expensive？

**Comment by mark86092** [comment]
@ensky 有想過 RegExp 其實很高成本，不過資料量在 1000 ~ 10000 筆內應該都在可接受的 10ms ~ 百ms，之後的確會考慮轉用別的方法搜尋（有考慮 elastic，但技術面上還在探索）

nodejieba 是個好建議，不過還想測試看看現在的資料上，搜尋的效果如何

schema versioning 要麻煩你提示，沒有實做過 (剛剛查到 https://github.com/emirotin/mongodb-migrations 這個？)，Thank you

**Comment by ensky** [comment]
@mark86092 那就等你們測試的結果囉～若覺得 nodejieba 切 token 之後搜尋的結果還行的話那麼再來做接下來的事情～可以先用我的那版本測試看看效果怎樣，或是在這裡測試切 token
https://cppjieba-webdemo.herokuapp.com/

schema versioning 我之前只做過 pgsql 的，不過應該大同小異。大概就是每次 db schema 有變動的時候都給它一個版本號，比方說從 1 開始 serial 增加，然後每個版本號會跟著一個 migration 的 script，若現在 database 到哪個版本就執行 > 他的 migration script 直到最新的這樣。

在這個 case 的話因為 mongo 目前的中文 full text index 看起來支援不太完整，因此需要手動切完 token，因此就需要 migration 把舊的資料的 full text index 重新建立出來，這樣才搜得到舊的資料。另外公司名稱也可以考慮用同樣方式處理。

你貼的那個我沒用過，但看起來 mongo 的 migration 實做大概就長那樣，這個也是
https://github.com/afloyd/mongo-migrate
