### ISSUE TITLE
Reset internal data when start a `job_title` new search

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#24]
![image](https://cloud.githubusercontent.com/assets/1908007/16490955/5ed35124-3f0e-11e6-82f4-7bb7c342482f.png)

**Comment by barry800414** [comment]
這個問題沒有很懂

**Comment by barry800414** [comment]
by 彥齊:
我來說一下這個為什麼有問題
當我們查詢的時候，
如果查詢失敗（rejected），View 的 current\* 都不會動
然後View 就會根據這些update，重新顯示
所以，第一次我們查詢 行銷企劃人員 ok，成功
所以 currentWorkings 就會儲存查到的東西
第二次，我們再查詢 111，失敗（因為沒資料）
所以 currentWorkings 不會變更，所以會重新顯示 過去的東西
於是就產生問題了

**Comment by barry800414** [comment]
應該已經解決了，皆下來剩讀取Spinner的問題
