### ISSUE TITLE
工時允許 floating number

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#243]
原本的欄位看起來只能輸入整數，而且檢查的時候，也是用 parseInt
- [x] 將 placeholder 修正，提示成可以輸入小數
- [x] 將送出前的 check 修正，避免 -0.5 會通過檢查(parseInt is wrong)
- [x] Ajax 送出前，確保欄位是 float 轉文字，沒有非數字字元
- [ ] 資料顯示的部分，只顯示兩個位數
- [x] 等待後端更新

**Comment by barry800414** [comment]
Please merge after #246

**Comment by barry800414** [comment]
![image](https://cloud.githubusercontent.com/assets/3805975/17281006/bf4b2a52-57ca-11e6-9d76-102fe41f77ea.png)
已經看到有小數點的工時，這是正常的嗎XD?

**Comment by mark86092** [comment]
前端送過來的資料沒有確保是否是整數，所以小數點通過檢查，後端已經打勾修正成接受浮點數，所以就變成圖看到的了

**Comment by mark86092** [comment]
Feature：資料顯示的部分，只顯示兩個位數 will be solved future
