### ISSUE TITLE
表格區(3) 的placeholder 加入"例如:" ，避免以為預設已經填入

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#246]
表格區(3) 的placeholder 加入"例如:" ，避免以為預設已經填入

工作日表訂工時:     例如: 8
實際平均工時:  例如: 10
一週總工時:  例如: 40

**Comment by barry800414** [comment]
應該不用這個issue了，#243去修就好

**Comment by mark86092** [comment]
把 #243 的 check list 標注一下吧～
