### ISSUE TITLE
上方橫條因為白色而看不見

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#25]
![image](https://cloud.githubusercontent.com/assets/1908007/16491101/2e33a748-3f0f-11e6-8bca-e90c6b7eadc9.png)

**Comment by barry800414** [comment]
對，我剛嘗試要解這個問題，但解的不太好QQ
有個問題是，首頁字需要是白色，因為有大張的圖。

**Comment by mark86092** [comment]
或許可以這裡也放圖？
