### ISSUE TITLE
Form error hint

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#250]
當使用者在填寫表單的時候，常會發生，按下送出才知道錯誤，是否能改善 錯誤提示 讓使用者經驗更好？

想到的解法：

1) 利用 Bootstrap 提供的 [Validation State](http://getbootstrap.com/css/#forms-control-validation)，當使用者按下送出後，將不符合的欄位標色

2) 利用 Bootstrap 的 [tooltips](http://getbootstrap.com/javascript/#tooltips) 來提示訊息

3) 捲動視窗至表單頂部

不符合的欄位定義：(a) 必填的欄位沒填、(b) 欄位的值不符合預期範圍

上面的 1), 2), 3), (a), (b) 都可以組合

**Comment by barry800414** [comment]
我的想法是 
(a)必填的欄位沒填的話，在使用者un-focus那個格子的時候，邊框就上色& 加上tooltips 
(b)欄位的值有問題的話，就是彥齊你原本說的 (1)->(2)->(3)

**Comment by barry800414** [comment]
遇到幾個問題
1. jquery UI裡面 tooltip本身的功能是，hover or click下去才會出現tooltip。我嘗試call $(..).tooltip("open")，他也不會主動打開tooltip
2. bootstrap裡面validation state的功能，原本是可以加icon的 ([ref](http://getbootstrap.com/css/#forms-control-validation)) ，但是下面因為有用addon顯示「小時」，兩個一起用會疊在一起
   像這樣: ![default](https://cloud.githubusercontent.com/assets/3805975/17203869/801ce576-54d4-11e6-93de-9fb10a5c0efb.PNG)
   這似乎是個bootstrap的[issue](https://github.com/twbs/bootstrap/issues/12551)

**Comment by mark86092** [comment]
For the 1) part, please see http://getbootstrap.com/javascript/#markup-1, it allow you the generate static tooltip

For the second part, I think the color hint is OK. The icon is not necessary

**Comment by barry800414** [comment]
我嘗試用bootstrap裡面tooltip("show") & tooltip("hide")的功能。第一次顯示沒有問題，但可能第一次填錯之後，再填錯的然後換掉message再call一次tooltip("show")，會沒有用...


Branch: https://github.com/goodjoblife/WorkTimeSurvey/tree/form-warning
做法:
https://github.com/goodjoblife/WorkTimeSurvey/blob/form-warning/js/index.js#L252

**Comment by barry800414** [comment]
問個問題，有tooltip的話，我們還需要上傳按鈕上方的錯誤訊息嗎?

**Comment by mark86092** [comment]
Seem the prompt message is not necessary.
If you fix it, PLEASE add to your PR's checklist
