### ISSUE TITLE
用手機瀏覽網站，點表格時，不要自動放大

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#257]
用手機瀏覽網站，點表格時，不要自動放大。旁邊的按鈕就被擠掉，還要手動縮小，很不方便。
有可能點input的時候不要放大，但使用者用兩根手指頭放大的時候還是可以放大嗎?

**Comment by barry800414** [comment]
剛實測這個解法，還是有時候會zoom in 
ref: https://www.dynamo6.com/blog/how-to-prevent-unwanted-zooming-on-mobile-devices/

ref: http://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by peteranny** [comment]
有試過font-size:16px嗎，感覺是最正統解法，如果不太影響layout的話

**Comment by mark86092** [comment]
再確認一下現在的問題存在嗎？

**Comment by barry800414** [comment]
#267 以前的issue都是舊版網頁的issue
有些在新版上可能就已經解決了!
我也會一個一個看

**Comment by barry800414** [comment]
Has been solved
