### ISSUE TITLE
新增加班費的欄位

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#259]
目前是確定要新增這個欄位，但表格區要如何顯示、查詢工時區要如何顯示還沒決定。
先討論「表格區要如何顯示」

多排的radio button
![01](https://cloud.githubusercontent.com/assets/3805975/17314546/d6d99280-5897-11e6-9fb1-4a76a7ee291f.PNG)

下拉式選單
![02](https://cloud.githubusercontent.com/assets/3805975/17314485/673deeee-5897-11e6-834b-0b988bc220b1.PNG)

我覺得下拉式選單better。
Please comment it.

**Comment by mark86092** [comment]
只有 radio, 不要 button 的情形呢？

**Comment by barry800414** [comment]
![03](https://cloud.githubusercontent.com/assets/3805975/17314881/20c871de-589a-11e6-8553-5811b5bbb47f.PNG)

**Comment by barry800414** [comment]
跟據第10次會議，新增的欄位不太一樣。 so close it
