### ISSUE TITLE
I13N for landing page (GA)

### ISSUE THREAD

**Issue by qcl** [goodjoblife/WorkTimeSurvey#26]
重新整理一下要埋GA的地方 (by Wei-Ming
- [x] load GA script into landing page
- [x] Tracking fb sign in button click event
- [x] Tracking input box on focus click event
- [x] Tracking submit button click event
- [x] Tracking modal-fb-sign-in button click event
- [x] Tracking uploading successful/failed event
- [x] Tracking checking form failed event
- [x] Tracking share button event  
- [x] Tracking navigation bar click event

**Comment by mark86092** [comment]
可是不會 :P 想看怎麼做～

**Comment by qcl** [comment]
page view 的話已經都有了吧？我們現在看起來就是 landing page 和 show page

**Comment by qcl** [comment]
button click event 我會埋

**Comment by qcl** [comment]
有種似乎得等到 UI 大致底定才開始埋，就先讀文件好了XD

**Comment by mark86092** [comment]
Done
