### ISSUE TITLE
職稱輸入的部份，有沒有更好的方法?

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#267]
職稱輸入的部份，有沒有更好的方法，讓使用者選到我們設定的職稱。
以利我們做後續的統計?

(目前980筆資料中，只有301筆對的到)

我剛想到一個做法，目前104人力銀行的職稱分類，還是個「分類」，可能不是使用者直接會想到的。
如果我們去call 104 API把所有職缺撈下來，裡面應該會有 「職缺名稱」(公司留的) &「 職稱分類」(104的分類)。想辦法做個mapping from 職缺名稱 -> 職稱分類，然後之後都用職缺名稱的列表去做autocomplete? 

這個issue不急 & 需要比較多時間討論。

**Comment by mark86092** [comment]
先關掉
