### ISSUE TITLE
網頁載入速度的優化

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#268]
![default](https://cloud.githubusercontent.com/assets/3805975/17352623/a3ae7a78-596a-11e6-9006-4726304494bc.PNG)

我自己用iphone + safari載入真的很慢，要10幾秒。
目前的理解是字體的問題。

**Comment by barry800414** [comment]
some possible solution:
https://css-tricks.com/preventing-the-performance-hit-from-custom-fonts/
提到: Ajax in the fonts

https://davidwalsh.name/font-loading
提到 Use Non-Blocking CSS Loading

我覺得或許可以試試看? 就是不要讓它block在那邊，字整個不見，先顯示&讓使用者認為已經完成，再慢慢載入字體。

**Comment by mark86092** [comment]
你可以 implement 看看，不過，先回到最原始的問題：為什麼需要這個 1~2 MB 的字型？我記得本來的原意是要解決 win 上面的新細明體問題

**Comment by barry800414** [comment]
是阿，新細明體不好看。而且因為每個系統所擁有的字體不同，是有可能產生排版上的問題的。
基本上如果可以找到一個不難看，又每個系統都有的字體，我們是不用另外下載字體的。

**Comment by mark86092** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fworktime.goodjob.life%2F

A nice tool

**Comment by mark86092** [comment]
目前專案重構
