### ISSUE TITLE
首頁：工時資訊表單送出功能

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#276]
大約是原本的 https://github.com/goodjoblife/WorkTimeSurvey/blob/master/js/index.js 地方的 js
- [ ] Form
- [ ] FB sign in
- [ ] Form Validation
# 
- [ ] FB share
- [ ] Modal for more information
- [x] Click getting started

**Comment by barry800414** [comment]
是不是要改的話，要到 https://github.com/goodjoblife/WorkTimeSurvey-front-end 改?
我看這裡branch裡面是compile過的
