### ISSUE TITLE
首頁：自動完成 (autocomplete) 功能 js 轉移

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#277]
- [x] 首頁 表格區 - 公司自動完成
- [x] 首頁 表格區 - 職稱自動完成

original : https://github.com/goodjoblife/WorkTimeSurvey/blob/master/js/formUtility.js

**Comment by barry800414** [comment]
@wutingy  @mark86092  想問一下，因為jquery UI會有一份css檔，這個部份應該要怎麼處理呢?
這邊目前autocomplete已經接上，但介面還沒有辦法套上jquery ui的css

**Comment by mark86092** [comment]
可以的話，先去 jquery-ui 的網站抓一份 minimal 打包的東西，看一下

**Comment by wutingy** [comment]
css 可以放在 src/css/utilities  裡面

**Comment by barry800414** [comment]
@wutingy 我把jquery ui 的css放在src/css/utilities，看起來沒有work，感覺是gulp 的流程要去修改。
這個部份我還不太熟悉，看能不能看懂再去改，或者是由妳改。

另外昨天那個畫面跑掉的原因我找到了，不是js載入兩次的關係(concat的時候其實只有複製一份)，而是因為在cygwin按ctrl + C並沒有把watch的process砍掉，重覆操作下變成有一堆process在watch同一份檔案，一偵測到change就去覆寫同一份檔案，然後就爆炸了。

**Comment by wutingy** [comment]
忘記跟你說要把副檔名改成 `.pcss`，如果還是不能 work 我晚點看看。
