### ISSUE TITLE
測試網頁介面

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#288]
url: http://preview-f.goodjob.life/
### On Windows
- [ ] IE (版本: IE 11, by wei-ming)
  首頁表格，input介面跑掉
  ![image](https://cloud.githubusercontent.com/assets/3805975/18622228/21f758b4-7e5f-11e6-9364-3a479d560d70.png)
  查詢頁查詢欄，input介面跑掉
  ![image](https://cloud.githubusercontent.com/assets/3805975/18622240/38c47b6c-7e5f-11e6-88b1-31a7934de79d.png)
  查詢頁最新工時，不會顯示
  ![image](https://cloud.githubusercontent.com/assets/3805975/18622248/4bc31ade-7e5f-11e6-9772-664f3fbe3fe0.png)
- [x] Firefox (版本: 47.0.1 介面看起來沒問題 by wei-ming)
- [x] Chrome (版本: 53.0.2785.113 介面看起來沒問題 by wei-ming)
### On Mac OS
- [ ] Safari
- [ ] Firefox
- [ ] Chrome
### On iOS
- [x] Safari (on iphone 5)
- [x] Firefox
- [x] Chrome
### On Android
- [ ] native
- [ ] Firefox
- [ ] Chrome

**Comment by barry800414** [comment]
@wutingy  好像IE 11上面，input的介面就會跑掉

**Comment by wutingy** [comment]
ie 真的不支援 promise @@" 如果有需要用到再加上 polyfill。

**Comment by mark86092** [comment]
目前應該不會用到 promise (or use `$.ajax().promise()`)
