### ISSUE TITLE
show 頁面 搜尋框 改善

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#293]
1. 當最新工時（`/#latest`）時，搜尋框應該清空， radio 要回復預設值
2. 當切換至 search-and-group 相關的時候，搜尋框與 radio 要相對應改變

see discussion in #291

**Comment by homerchen19** [comment]
搜尋欄裡面如果什麼都不打
需要不讓他搜尋嗎？
目前網站會讓他搜尋空白，然後什麼都沒有跑出來ＸＤ

**Comment by mark86092** [comment]
搜尋 "" 應該有出現 **找不到結果**？至於怎麼處理要不要搜尋 @barry800414 覺得呢？

**Comment by barry800414** [comment]
感覺可以按下去沒有反應

**Comment by mark86092** [comment]
![image](https://cloud.githubusercontent.com/assets/1908007/18859427/78318bee-84a6-11e6-8874-f641dd19600a.png)

我的是這樣

**Comment by homerchen19** [comment]
我的也是這樣
我覺得要擋什麼都不打的情形

**Comment by barry800414** [comment]
點下去沒有任何反應比較直覺，搜""這件事滿怪的

**Comment by mark86092** [comment]
怎麼不是告訴使用者要填？

**Comment by wutingy** [comment]
沒有輸入東西的時候先 disable button (灰色/半透明 & hover 沒有手) 呢？

**Comment by mark86092** [comment]
或是加個？
![image](https://cloud.githubusercontent.com/assets/1908007/18859531/8ee2bde4-84a7-11e6-8f38-6c828eb8cdd3.png)

**Comment by wutingy** [comment]
加這在搜尋蠻怪的，因他只有一個 input 欄位
