### ISSUE TITLE
[查看工時頁面] flexbox 支援ios8

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#299]
1. support ios 8 (?) flexbox

**Comment by mark86092** [comment]
maybe cover not only ios8 but also some old env

**Comment by wutingy** [comment]
@mark86092 例如說？ios7 ?

**Comment by mark86092** [comment]
@wutingy 我看到你做完了，我本來是不知道會有哪些範圍出問題啦
