### ISSUE TITLE
[查看工時頁面] 介面小修正

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#302]
- [x] 最新工時的資料表格，上方加上「最新工時」的標題
- [x] 返回搜尋欄的icon，修改為至頂端的icon，並調整顏色

**Comment by wutingy** [comment]
- [x] 頁面過短時 footer 應要置底，或是加個 min-height
- [x] 展開不知為何會抖抖的
- [x] `.search-result { margin-bottom: 100px; }`

**Comment by mark86092** [comment]
展開的時候，我自己沒察覺到抖抖的（手機 & 電腦都還好）

**Comment by wutingy** [comment]
一點點... 底下會 bounce 一下 感覺很不爽，沒關係已修正
