### ISSUE TITLE
[資料填寫頁] 回饋總整理

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#303]
- [x] Menu bar的文字顏色調整 #304 
- [x] Autocomplete 移除提示字，但提示有這功能 #305 
- [x] input的placeholder文字調整 (8 或8.5) #306 
- [x] 錯字修正  (補"休") #306 
- [x] 與我們聯繫的icon調整 #304

**Comment by mark86092** [comment]
Done
