### ISSUE TITLE
[資料填寫頁] Menu bar的文字顏色 & 與我們聯繫的icon調整

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#304]
- [x] 與我們聯繫 messenger icon change to facebook icon
- [x] header menu color change to dark gray
- [x] 整體網站的英文字母 font weight (Android) 太細（各個平台有些不一）

**Comment by wutingy** [comment]
header menu 要改成深灰色。

@barry800414 

> 與我們聯繫的icon調整

這是什麼？我忘了@@

**Comment by mark86092** [comment]
@wutingy 是有一塊區域叫"與我們聯繫"，上面有一個 FB 的 icon
