### ISSUE TITLE
[資料填寫頁] Autocomplete 移除提示字，但提示有這功能

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#305]
目標: 讓使用者在輸入的時候，能夠意識到有自動完成的功能

**Comment by wutingy** [comment]
補充：討論出的做法是，input on focus 時， dropdown 出一個寫死的 array (常用的字詞)，避免 loading 延遲。讓使用者馬上知道這是可以自動完成的。

目前是要打兩個字元他才會開始 load 字詞出來。
