### ISSUE TITLE
[查看工時頁面] 搜尋欄，變數名稱未改，導致無法搜尋

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#317]
deCodeName 未改成 decodedName 
以下是其中一行
https://github.com/goodjoblife/WorkTimeSurvey/blob/dev/src/js/main/show.js#L202

**Comment by homerchen19** [comment]
抱歉沒改到ＱＱ
我再PR一次

**Comment by barry800414** [comment]
沒事的，只是之後有改的話要測試一下! 所有人都是!
