### ISSUE TITLE
手機載入網頁因為字體的關係很慢

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#32]
手機載入網頁因為字體的關係很慢，它不像電腦會先顯示字，字體下載好後才換字體。
而是整個字都不會出現，等下載完才出現。
這個issue還好，先把其它重要功能完成比較重要

**Comment by mark86092** [comment]
這個問題是因為 css 放在 head 裡，所以會等待字體載完，才進行下一步（Block rendering）

所以，要解這個問題，不知道把css移到</body>前有沒有用

**Comment by mark86092** [comment]
close after merge #37
