### ISSUE TITLE
我填寫送出然後變灰色的沒反應

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#330]
我填寫送出然後變灰色的沒反應
是否送出時可以用文字提示正在送出？
並說如果遲遲沒有回應可能是你網路慢可能重整再填一次

![screenshot_2016-10-06-19-09-19](https://cloud.githubusercontent.com/assets/7566586/19158793/aaafe548-8c1c-11e6-88a8-5942f7f38bae.png)

**Comment by mark86092** [comment]
可以提供可重製的流程

**Comment by peteranny** [comment]
回家測試後，重製不出來了

先暫時當作是網路不穩吧

**Comment by mark86092** [comment]
想問：1. 按下按鈕 --> 2. 按鈕變灰色 --> 3. 跳出FB登入視窗 --> 4. 允許FB權限 --> 5. FB視窗關閉

上面哪些沒有出現？

**Comment by peteranny** [comment]
因為我已經有登入了的關係，345通通沒出現
但按鈕按了沒反應，就是在2完就停了，重整後再填一次就送出成功了，沒有345

**Comment by mark86092** [comment]
我想要你幫我再確認一件事：現在看到的按鈕上面的文字是什麼？

如果有登入且授權過了，那應該345步會跳過沒錯，但按鈕文字應該如下圖

![image](https://cloud.githubusercontent.com/assets/1908007/19159761/2a692986-8c20-11e6-80e4-050aee1d8604.png)

**Comment by peteranny** [comment]
那沒錯，這是bug

我「以F認證並送出資料」按了沒送出，重整之後（好像）是「送出資料」，然後就送出了

**Comment by mark86092** [comment]
按鈕文字有變的判斷是從：FB js load --> FB log in --> callback change text 

所以，如果是 FB 整個慢掉，要想想怎麼更平滑了

**Comment by barry800414** [comment]
所以看起來是FB login的偵測出問題? 導致後來上傳出錯嗎?

**Comment by barry800414** [comment]
阿不過我說，這個當時發生的時候的螢幕截圖嗎?  上面的網路狀態，僅可撥打緊急電話?

**Comment by peteranny** [comment]
那是我另一張Sim卡，不用管他

**Comment by barry800414** [comment]
所以你的手機當時是有網路的嗎?

**Comment by mark86092** [comment]
應該要有，至少讀得到我們的網站

**Comment by peteranny** [comment]
有，但我在捷運上，所以網路不穩

**Comment by barry800414** [comment]
對的，我指的就是，後來網路不穩，所以送不出去。
感覺要加上:
1. 一定時間後取消request，這個做的到嗎?
2. 顯示讀取的圓圈圈

**Comment by mark86092** [comment]
怎麼得到網路不穩所以送不出去的結論？

**Comment by barry800414** [comment]
不確定是不是網路不穩，但如果網路不穩的情況下，送不出去，會給使用者response嗎?

**Comment by mark86092** [comment]
你說的送不出去是指： FB 的 request 還是我們的 request？

至於我們的 request 失敗（timeout）是會有訊息的（時間要條）
https://github.com/goodjoblife/WorkTimeSurvey/blob/master/src/js/main/index.js#L251

**Comment by barry800414** [comment]
我再看清楚一點好了，這樣看起來是不是FB的request沒有response的關係? 
還是無法辨識..

**Comment by mark86092** [comment]
我覺得要仔細檢查流程來看，不排除是網路失敗，也不排除 FB 當天有問題，也不能排除程式有問題
