### ISSUE TITLE
工作日的說明如果再少兩個字就不會斷行了

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#331]
工作日的說明如果再少兩個字就不會斷行了，實際平均也是
看要不要少幾個字讓手機版面好看一點點

![screenshot_2016-10-06-19-09-25](https://cloud.githubusercontent.com/assets/7566586/19158825/c5ac2c30-8c1c-11e6-960f-e73a8765d844.png)

**Comment by mark86092** [comment]
麻煩版面還有文字看看怎麼處理

**Comment by barry800414** [comment]
基本上我覺得這個不用調整，每個裝置螢幕大小不同，今天砍了兩個字，換個更小的螢幕，結果也會一樣。
