### ISSUE TITLE
是否list最後也可以放個橫bar按了也能收list

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#332]
看一種職位，list很長，拉到底看完後，想說把list收起來
如果每個list除了按panel title(有-的那行)以外，是否list最後也可以放個橫bar，按了也能收list?

![screenshot_2016-10-06-20-23-16](https://cloud.githubusercontent.com/assets/7566586/19158844/d09f285e-8c1c-11e6-9bd6-0ba91e6998eb.png)

**Comment by barry800414** [comment]
你的意思是，(-)這個按鈕，在那個group的底下也出現?

**Comment by wutingy** [comment]
設計上是不建議這麼做，會有點 confused，不過可以改成手機上整塊都是點選範圍，與 fb app 使用情境一樣

**Comment by peteranny** [comment]
我想像的不是底下也一個-，大概是像一個細細的橫bar，裡面有個上三角符號，就看得出來是收list的意思，而且細細的也不致影響layout

如果整個都是點選範圍，就怕滑動時會很容易按到

**Comment by wutingy** [comment]
是可以～～如果大家覺得有必要的話可以加，我個人是覺得還好

**Comment by mark86092** [comment]
拉到底看完想把list收起來是因為要回到頁面上方嗎？我知道iphone可以直接回到頁面上，android應該會點向上紐或上一頁

**Comment by peteranny** [comment]
頁面上方的話tin已經有做按鈕了
我是想收起來那個公司，這樣比較好看其他公司，我喜歡一次開一個看

這我個人習慣啦，看有沒有別人也需要

**Comment by mark86092** [comment]
那這個 issue 就先關起來囉，等到之後有人有同樣的需求時，會在打開做討論
