### ISSUE TITLE
筆數不足5筆從-改成明確的”資料不足”？

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#333]
筆數不足5筆用-表示還是有點怪，讓我感覺乾脆不要顯示好了
但又不能不顯示，還是說-就改成明確的”資料不足”？

![screenshot_2016-10-06-20-21-47](https://cloud.githubusercontent.com/assets/7566586/19158877/e938b8b2-8c1c-11e6-8dd2-35879811d9eb.png)

**Comment by barry800414** [comment]
不太能不顯示，這樣不會意識到有這個欄位。
不過我也覺得現在只有寫"僅顯示五筆以上"的提醒不夠明顯，如果可以 - 換成字，我也覺得比較好。

@wutingy

**Comment by wutingy** [comment]
換成文字我覺得也 ok!

**Comment by mark86092** [comment]
那就討論看看要寫成什麼了

**Comment by barry800414** [comment]
我的想法是，在加班有無加班費、加班有無補休的字旁邊，加上 「資料尚未達五筆，尚無法顯示」
不然 - 要改成很短的字不太容易
排版上可能會出問題，但可以先做沒關係。

**Comment by peteranny** [comment]
我覺得寫成「資料尚未達到五筆以上，達到了再顯示：）」之類的，比較可愛

**Comment by barry800414** [comment]
我覺得好阿~!

**Comment by barry800414** [comment]
@xxhomey19  這個issue，想麻煩你在這個週日 (10/23)之前，開PR

**Comment by mark86092** [comment]
Done, #345
