### ISSUE TITLE
查公司的和查職稱的input value在切換時要分開記?

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#334]
如果在查公司時輸入query，再按查職稱的radio，是否此時把input清空會好一點？
應該說，查公司的和查職稱的input value在切換時要分開記，如果又點回查公司可以restore查公司的input value

**Comment by barry800414** [comment]
這個，基本上我覺得現在或你說的方法都可以。
你說的做法的缺點是，現在預設是公司，如果使用者就先輸入了職稱，你換成職稱，就清空了，它應該覺得很煩

這個，問一下 @wutingy 好了

**Comment by wutingy** [comment]
會很煩 +1 分開記的目的是？

**Comment by peteranny** [comment]
講這個是因為通常我按了radio就是想搜另一個，這時input沒自動清空有點煩，分開記是想說按回來input還可以restore

不過我的確沒考慮到先填input才按radio的狀況那這應該無解了
