### ISSUE TITLE
建議 "必填加*" 改成 "選填加(選填)"

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#335]
必填欄位曾經看過有人建議不要用 \* ，因為 \* 是符號，不太提醒到人哪個必填哪個選填
有人建議說讓必填欄位不要加符號，而選填欄位加(選填)

![screenshot_2016-10-06-19-09-25](https://cloud.githubusercontent.com/assets/7566586/19159112/d17f93d4-8c1d-11e6-98ea-2d7594cf5500.png)

**Comment by wutingy** [comment]
我個人是偏向打星星，因為大家基本上有在用電腦的都會知道，在 label 後面括弧選填資訊會亂，且我們有做 alert 提醒他必填，如果他離開沒填的話。
