### ISSUE TITLE
F登入

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#336]
在瀏覽器打開，載入之前cache的網頁狀態，也就是這不是重整載入的網頁，然後在這個session按F登入一直失敗，我不知道是不是和cache有關，可能直接code看什麼時候登入失敗比較準？

(然後一樣，重整就好了，然後果然那個button改變文字的latency很有感，也許改成在確認F是否已登入前，button都設成不能按比較好？

**Comment by barry800414** [comment]
其實有點看不懂0.0  F是什麼?

**Comment by peteranny** [comment]
Facebook

**Comment by peteranny** [comment]
不過我知道這bug很不夠精確，我暫時也無法重製，所以先知道有這件事就好

**Comment by barry800414** [comment]
我有個疑問，怎麼知道自己的網頁是在cache的狀態下呢?

**Comment by mark86092** [comment]
你們說的 cache 出問題，是指哪個檔案出問題？導致無法登入？

我看不出來 cache 和 F 登入有關

**Comment by peteranny** [comment]
就我的瀏覽器關掉再打開會保留網頁狀態
恩想想我也覺得應該沒關係

我這裡重點是想提議按鈕在確認F是否登入前都先disabled

**Comment by barry800414** [comment]
我覺得在確認facebook登入的這段時間，可以加上loading的圓圈圈，並且disable。
然後 @peteranny  ，這個issue可以給你解嗎

**Comment by peteranny** [comment]
你們之前弄的loading的圓圈圈是怎麼來的，圖片？還是什麼

**Comment by barry800414** [comment]
我之前是用圖片，不過Tin可能有換，要去挖一下
如果loading那個找不到的話，可以先註記一下那個地方給Tin處理

**Comment by wutingy** [comment]
i use base64 code for loading gif, is't on CSS file.
