### ISSUE TITLE
[Question] window.fbAsyncInit may always be called ?

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#337]
### 結論

`index.js` 上面的 FB callback (`window.fbAsyncInit`) 每次都會被執行到嗎？
### 原因
1. 在 [_layout.pug#L37](https://github.com/goodjoblife/WorkTimeSurvey/blob/master/src/views/_layout.pug#L37) 當中，匿名函數立刻執行 async loading FB SDK 
2. 在 [_layout.pug#L55](https://github.com/goodjoblife/WorkTimeSurvey/blob/master/src/views/_layout.pug#L55) 可以讓 `index.pug` 讀取 `index.js`
3. 在 [index.js](https://github.com/goodjoblife/WorkTimeSurvey/blob/master/src/js/main/index.js#L279)，window.fbAsyncInit 被宣告

想問是不是有可能 index.js  被讀取好到解析這段過程當中，發生了 FB SDK 先被解析的情況，導致 fbAsyncInit 未定義，所以就沒有執行到該有的驗證？

**Comment by barry800414** [comment]
剛剛嘗試在看doc:
1. https://developers.facebook.com/docs/javascript/quickstart
2. https://developers.facebook.com/docs/facebook-login/web

雖然不確定有沒有特定順序的問題，但看起來 window.fbAsyncInit 都是先宣告好，呼叫 `(function(d, s, id) {`。
然後 

```
FB.getLoginStatus((response) => {
    statusChangeCallback(response);
  });
```

看起來不用埋在 `window.fbAsyncInit` 裡面，所以其實可以放到 _layout.pug裡面?
或者是，整份基本的FB SDK init (第1個doc所寫的)，獨立放到global裡面的js

**Comment by mark86092** [comment]
@barry800414 `FB` 的其他方法（例如：getLoginStatus）需要在 FB.init() 後才可以，

至於 FB SDK 怎麼 load 應該可以移動看看

**Comment by barry800414** [comment]
我可能要禮拜二才能試試看，家裡的電腦npm install裝不好package，無法測試，滿奇怪的

**Comment by barry800414** [comment]
我的結論有錯

```
FB.getLoginStatus((response) => {
    statusChangeCallback(response);
  });
```

這一段必須要在 `window.fbAsyncInit` 裡面才對
