### ISSUE TITLE
問卷表單送出後，如果伺服器端傳回錯誤代碼，沒有處理

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#34]
如圖，這是一個 company_id 不存在的情況，所以當收到錯誤的時候，應該要做提示或處理

![image](https://cloud.githubusercontent.com/assets/1908007/16512865/518e07c8-3f92-11e6-960a-0f3dd6e1d92f.png)

**Comment by barry800414** [comment]
statusText, responseText, 哪一個才是error message?

**Comment by mark86092** [comment]
status: 是http code, statusText 是根據 code 的解釋（這個是內部處理的）

responseText 是我回傳的資訊，responseJSON 是 jQuery 轉換的
