### ISSUE TITLE
預覽圖片看不見

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#347]
從縮圖預覽的圖片出錯，尋找可能的圖片來源，找到

![image](https://cloud.githubusercontent.com/assets/1908007/19656572/264690a0-9a53-11e6-8f63-64ff5b58bfe0.png)

![image](https://cloud.githubusercontent.com/assets/1908007/19656585/3466dbcc-9a53-11e6-93c9-2ea05bbf5eab.png)

圖片是透過 FB 讀取：https://worktime.goodjob.life/img/og-image_1200-630.png 這張圖片

所以，看不到圖猜測是因為圖片不見了

**Comment by barry800414** [comment]
看起來這真的是個FB的bug

從這邊 https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fworktime.goodjob.life 
看:
![image](https://cloud.githubusercontent.com/assets/3805975/19678004/831d5842-9ace-11e6-95e7-fd2bd90d4e48.png)

og:image的path已經更新了，但那篇置頂貼文沒有更新。
