### ISSUE TITLE
新增欄位

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#353]
整理幾個 feedback

1. 這是我的看法：能不能不要給選單預設是全職，而是請選擇？
![image](https://cloud.githubusercontent.com/assets/1908007/20207238/d9c4f358-a820-11e6-8c2e-7b27e422985f.png)

2. @xxhomey19 的建議：加班頻率這四個選項是否能多個重設呢

3. 手機介面調整

**Comment by mark86092** [comment]
感謝 @wutingy

ping @barry800414 你看一下 :P

**Comment by wutingy** [comment]
@mark86092 

> 不要給選單預設是全職

主要的考量點是什麼？

**Comment by mark86092** [comment]
我是考量如果使用者忘記填，就會預設是選全職了

**Comment by barry800414** [comment]
1. 關於這個，我覺得應該不致於忘記填?
2. 感覺可以加上個重設，如果畫面上塞的下的話

**Comment by wutingy** [comment]
(2) 這邊我想了很久...覺得再加個重設真的不是很好（畫面變得蠻亂的）如下圖。

建議是當使用者點選該選項就 uncheck（使用行為像 checkbox），雖然不太一目了然，但是至少有提供他清空的選項，只是不知道如果這樣的話，下方的「重設」按鈕行為是否一致比較好 @@

![screen shot 2016-11-19 at 20 58 43](https://cloud.githubusercontent.com/assets/8353239/20455672/5b8fdd04-ae9c-11e6-95af-d1a1ade1528b.png)

**Comment by mark86092** [comment]
幫 @wutingy 的建議 +1

**Comment by barry800414** [comment]
就如 @wutingy 說的! 就都一致，不要有重設，點兩次可以取消選擇這樣!

**Comment by barry800414** [comment]
另外職務型態的部份，我有修正我的想法，我認為預設還是請選擇比較好! 
#362 這個issue有提到!
