### ISSUE TITLE
查詢公司工時的部份，加班費/補休顯示方式的調整

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#357]
前一陣子朋友反應說，當加班費/補休欄位未滿5筆的時候，整欄都是-，會看不懂是什麼意思。
我想說，如果未達5筆，把藍色這塊隱藏起來如何呢?

![image](https://cloud.githubusercontent.com/assets/3805975/20294835/0a6f9ab2-ab3c-11e6-8af3-087db8cf91a9.png)

**Comment by wutingy** [comment]
![screen shot 2016-11-15 at 3 31 21 pm](https://cloud.githubusercontent.com/assets/8353239/20296957/dcd2fb5a-ab48-11e6-9f5b-dd273bee497c.png)

之前有畫一個這樣的版本，覺得呢？

**Comment by mark86092** [comment]
喔喔喔！！原來有上面這個版本！！！

**Comment by barry800414** [comment]
覺得可以!  如果不麻煩的話，想麻煩 @wutingy 改成這個!

**Comment by wutingy** [comment]
好喔～ 沒問題

**Comment by wutingy** [comment]
剛剛發現一個錯誤，`v-show="g.count <= 5"` 我看後端處理出來的資料應該是 `v-show="g.count < 5"` 才是吧？

**Comment by mark86092** [comment]
@wutingy OK, I'll fix it

**Comment by wutingy** [comment]
@mark86092 我正在改這邊的 style 我來～

**Comment by mark86092** [comment]
我想說這是 bugfix，所以可以麻煩你從 master branch 出修這個嗎？不想等下次 release 才將bug修正上線

**Comment by wutingy** [comment]
喔 對齁 好

**Comment by barry800414** [comment]
fixed by #365
