### ISSUE TITLE
工作資訊查詢頁面 - 以公司查詢的資料串接更新

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#358]
後端API: https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/129
請用原本的vue去新增新的欄位即可

**Comment by peteranny** [comment]
什麼叫作用原本的vue去新增新的欄位？
剛看了code，前端的UI寫好了，欄位的值也寫在js裡了，不太懂要做什麼新增

**Comment by barry800414** [comment]
- [x] vue的data binding 

例如:
https://github.com/goodjoblife/WorkTimeSurvey/blob/dev/src/views/partials/_show_search_and_group_by_company.pug#L71
職稱是以前就有的欄位，也用vue接起來了，像這個: `{{working.job_title}}`

https://github.com/goodjoblife/WorkTimeSurvey/blob/dev/src/views/partials/_show_search_and_group_by_company.pug#L87
這邊是新的欄位，vue的部份還沒加上去。目前是寫死的text。
- [x] vue的前處理

https://github.com/goodjoblife/WorkTimeSurvey/blob/dev/src/js/main/show.js#L145
像這個是後端拿到的data，跟顯示上會有一點點不同。
我們新增的欄位中，薪資&資歷都有類似的狀況。

**Comment by barry800414** [comment]
已更新，關掉這個
