### ISSUE TITLE
group-by-company/job_title 查詢結果可否也可點選

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#363]
想說，show的最新工時可點選公司變公司查詢，點職位變職位查詢，那進到公司/職位查詢後，可否讓查詢結果的公司/職位也都可以按，讓他可以繼續點選查詢其它公司/職位？

**Comment by mark86092** [comment]
我覺得ＯＫ，雖然這個功能不多人用

**Comment by barry800414** [comment]
我也覺得OK，就送個PR，如果想加這個功能吧!
