### ISSUE TITLE
【查詢資訊權限】 檢查查詢資訊的權限。 並做相對應的介面調整、功能限制。

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#373]
進入查詢資訊頁面後:

一開始是沒有權限的，需要將查詢功能鎖住。 詳見: #374 #375

1. 檢查是否已經登入，跟FB要token  
--未登入--> 顯示要先登入，檢查是否有權限。
--登入，並取得token -> 2 

2. 檢查是否有查詢權限 [API doc](https://github.com/goodjoblife/WorkTimeSurvey-backend/wiki/API-Endpoint-3.x#%E6%AA%A2%E6%9F%A5%E4%BD%BF%E7%94%A8%E8%80%85%E6%98%AF%E5%90%A6%E6%9C%89%E6%9F%A5%E8%A9%A2%E8%B3%87%E8%A8%8A%E6%AC%8A%E9%99%90) 
--沒有--> 顯示要留下一筆資訊或邀請一位使用者留下一筆資訊，才會有權限。 這個部份需要打API取得使用者推薦字串，詳見3。
--有--> 將查詢功能打開。

3. 取得該使用者推薦字串(給其他使用留資訊時的參考字串)，產生給使用者複製的網址
[API doc](https://github.com/goodjoblife/WorkTimeSurvey-backend/wiki/API-Endpoint-3.x#%E5%8F%96%E5%BE%97%E4%BD%BF%E7%94%A8%E8%80%85%E6%8E%A8%E8%96%A6%E5%AD%97%E4%B8%B2)
網址像這樣:  `https://worktime.goodjob.life/?rec_by=ooxx`

本issue需在 #374 #375 完成後，一併完成

Other ref: 
[FB Login](https://github.com/goodjoblife/WorkTimeSurvey/blob/28dfda883b38a839f73db0cef8e7287986ec2546/src/js/main/index.js#L309)

**Comment by barry800414** [comment]
@peteranny  這邊昨天沒有講清楚，還有一個步驟，是在使用者有登入但沒權限的情況下，需要做的事情。
是去打API，取得該使用者的推薦字串，用來產生網址 `https://worktime.goodjob.life?rec_usr=ooxx`用的

**Comment by peteranny** [comment]
這部分沒懂，私訊聊

**Comment by peteranny** [comment]
In branch show-auth:
src/js/main/show.js: testSearchPermission()
