### ISSUE TITLE
【查詢資訊權限】 限制/開放 以職稱&以公司查詢的功能

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#374]
#373 的子任務，should be done before #373
- [x] 限制以職稱&以公司查詢的功能
- [x] 開放以職稱&以公司查詢的功能

這一個issue僅須把功能以函數的方式完成，實際執行的部份交給 #373

**Comment by peteranny** [comment]
In branch user-enabled:
src/js/main/show.js: changeUserEnabled()
