### ISSUE TITLE
【查詢資訊權限】 限制/開放 單筆資訊查詢

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#375]
#373 的子任務，should be done before #373

- [x] 限制單筆資訊查詢的功能: 
      只能查到最新工時的前10筆資料。(以資料時間排序、最新到最舊的部份)
      其它排序放式的下拉選單應該要被disable。              
- [x] 開放單筆資訊查詢的功能

這一個issue僅須把功能以函數的方式完成，實際執行的部份交給 #373

**Comment by peteranny** [comment]
In branch show-auth:
src/js/main/show.js: changeUserEnabled()
