### ISSUE TITLE
【查詢資訊頁面更新】 單筆薪時資訊，排序功能、欄位更新、網址設計

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#376]
- [x] 排序功能 
- [x] Data Binding
- [x] 網址設計 (意指網址會根據query去變更)
- [x] 網址跳轉(舊版本的網址跳轉到新版網址)
[前端網址設計文件](https://docs.google.com/document/d/14DdYrWTYJzr0FN3r7Myvs-9ka-Se1669QEFGEonzXC4/edit?usp=sharing)

詳細欄位請見: [API doc](https://github.com/goodjoblife/WorkTimeSurvey-backend/wiki/API-Endpoint-3.x#%E5%96%AE%E7%AD%86%E8%96%AA%E6%99%82%E8%B3%87%E8%A8%8A)

**Comment by barry800414** [comment]
估算時薪的排序的部分，網址沒有按照doc:
https://docs.google.com/document/d/14DdYrWTYJzr0FN3r7Myvs-9ka-Se1669QEFGEonzXC4/edit?usp=sharing

![image](https://cloud.githubusercontent.com/assets/3805975/21953418/3cfd128e-da71-11e6-86e0-d0674a279639.png)

**Comment by mark86092** [comment]
@xxhomey19 can you fix it?
