### ISSUE TITLE
dev::show.html not working right under Firefox

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#381]
show.html在設定成user_enabled=false的結果(使用者無權限)，在不同的瀏覽器結果不同

在Chrome底下是對的：
![2017-01-12 10 50 53](https://cloud.githubusercontent.com/assets/7566586/21894306/a6f785b0-d919-11e6-9d77-d950b62214b7.png)

但用Firefox：
![2017-01-12 10 51 08](https://cloud.githubusercontent.com/assets/7566586/21894307/a73b2428-d919-11e6-9e09-22acaad0fa58.png)

若已登入，在被加入開發人員後在Chrome和Firefox皆正常
但未登入時，Chrome可顯示登入的提示，而Firefox則異常
所以是瀏覽器issue

**Comment by peteranny** [comment]
不過彥齊說是hot loading的問題，所以不知道是不是說這個bug不一定重製得出來？

**Comment by mark86092** [comment]
應該只是開發上暫時的問題
