### ISSUE TITLE
[查詢資訊頁面] 以公司、職稱查詢、工時排行、時薪排行榜，在使用者沒有權限的處理

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#397]
![image](https://cloud.githubusercontent.com/assets/1908007/21963707/44dea5bc-db7a-11e6-9ffb-62c5ab520923.png)

如圖，

1) 需要跳轉回 "最新薪時" 頁面

**Comment by barry800414** [comment]
這邊補充一下，除了最新薪時的頁面外，其他的頁面在沒有權限的情況下，應該要跳轉過去最新薪時的頁面。

**Comment by wutingy** [comment]
BTW 未登入的時候，下方兩顆按鈕應該要隱藏

**Comment by mark86092** [comment]
@wutingy 沒理解，登入但沒有查詢權限的時候呢？

**Comment by wutingy** [comment]
@mark86092 登入但沒有查詢權限的時候，他們才會出現。因為這樣才有連結給他分享

**Comment by mark86092** [comment]
@wutingy 麻煩你幫忙開一個 issue，這個要列入修正了

**Comment by wutingy** [comment]
https://github.com/goodjoblife/WorkTimeSurvey/pull/404

**Comment by barry800414** [comment]
總共有以下幾種情況要跳轉回最新薪時 `/latest`，我盡量說清楚:
單筆資訊的部分:
1. `/sort/time-asc` (以時間排序由舊到新)
2. `/work-time-dashboard` (以週工時排序由大到小，也就是工時排行)
3. `/sort/work-time-asc` (以週工時排序由小到大)
4. `/salary-dashboard` (以估計時薪排序由大到小，也就是時薪排行)
5. `/sort/salary-asc` (以估計時薪排序由小到大)

以職稱查詢:
1. `/job-title/:job_title/work-time-dashboard`  (以週工時排序由大到小)
2. `/job-title/:job_title/sort/work-time-asc` (以週工時排序由小到大)
3. `/job-title/:job_title/salary-dashboard` (以估計時薪排序由大到小)
4. `/job-title/:job_title/sort/salary-asc` (以估計時薪排序由小到大)

以公司查詢:
1. `/company/:company/work-time-dashboard`  (以週工時排序由大到小)
2. `/company/:company/sort/work-time-asc` (以週工時排序由小到大)
3. `/company/:company/salary-dashboard` (以估計時薪排序由大到小)
4. `/company/:company/sort/salary-asc` (以估計時薪排序由小到大)

也就是除了 最新薪時 `/latest` 以外，在使用者沒有權限的情況下，都要跳轉到 `/latest`

@peteranny

**Comment by peteranny** [comment]
整個code，除了GA以外我沒有搜尋到`/latest`這個字樣.........
所以我不知道什麼叫作跳轉到`/latest`

**Comment by barry800414** [comment]
[前端網址設計文件](https://docs.google.com/document/d/14DdYrWTYJzr0FN3r7Myvs-9ka-Se1669QEFGEonzXC4/edit?usp=sharing)
是這一份文件，嗯，開issue的時候沒有講清楚。

**Comment by peteranny** [comment]
我現在要依照新的對照來寫？還是先沿用舊的？？
