### ISSUE TITLE
【查詢資訊頁面更新】單筆資料、以公司/查詢時的標題

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#398]
我指的是這個標題[最新工時資料]的部分，應該要依據網頁查詢的內容變動
![image](https://cloud.githubusercontent.com/assets/3805975/21964034/363341d0-db7f-11e6-97a4-45bc98ba7141.png)

#### 單筆資訊:
`/latest` -> 最新薪時資訊
`/sort/time-asc` -> 最舊薪時資訊
`/work-time-dashboard` 或  `/sort/work-time-asc` -> 工時排行榜
`/salary-dashboard` 或 `/sort/salary-asc` -> 估計時薪排行榜

#### 以公司查詢:
全部都用 `以 COMPANY 查詢的薪時資訊` 就好

#### 以職稱查詢: /job-title/:JOB_TITLE/sort/:GROUP_SORT
假設職稱是`JOB_TITLE`，when `GROUP_SORT`:
`/work-time-dashboard` 或 `/sort/work-time-asc` -> `JOB_TITLE`的工時排行榜
`/salary-dashboard` 或 `/sort/salary-asc` -> `JOB_TITLE`的估計時薪排行榜

**Comment by mark86092** [comment]
@barry800414 

#421 使用的是 Filters 

https://vuejs.org/v2/guide/syntax.html#Filters

這裡提到 `For more complex data transforms in other directives, you should use Computed properties instead.`

麻煩參考這裡：https://vuejs.org/v2/guide/computed.html#Basic-Example

Filter 會寫在 component 外，對日後要找的人不容易（特別是這個 filter 只針對一個 component 有效）

故 #421 合併後，麻煩再持續針對這個 issue 作改善

**Comment by barry800414** [comment]
原來有這種東西，就想說有沒有類似component 內的filter
我會再送PR上來
