### ISSUE TITLE
以公司查詢、以職稱查詢的API Endpoint未修正

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#406]
https://github.com/goodjoblife/WorkTimeSurvey/blob/dev/src/js/main/show.js#L152
https://github.com/goodjoblife/WorkTimeSurvey/blob/dev/src/js/main/show.js#L210

**Comment by mark86092** [comment]
看不懂，需要列出要修正的點

**Comment by barry800414** [comment]
我知道了QQ，我看錯了。是三種API都沒有丟access_token上去。
