### ISSUE TITLE
[查詢資訊頁面] Firefox 私密瀏覽模式下，追蹤保護的功能會讓fb SDK, GA SDK無法載入

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#418]
不知道算不算一個問題
Firefox 私密瀏覽模式下，追蹤保護的功能會讓fb SDK, GA SDK無法載入
![image](https://cloud.githubusercontent.com/assets/3805975/22089548/d2053308-de26-11e6-813c-0cd97890d837.png)

會導致登入功能無法使用

**Comment by mark86092** [comment]
這個應該沒辦法處理

**Comment by barry800414** [comment]
ok, close it.
