### ISSUE TITLE
[查詢資訊頁面] 估計時薪、參考時間  提示字

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#422]
估計時薪、參考時間的地方，hover過去希望有提示字，或者是有個?可以按，顯示提示字

估計時薪的提示字:
```
時薪估計方式：
1. 當薪資種類為「時薪」：無需估算
2. 當薪資種類為「日薪」：以 日薪 ÷ 工作日實際工時 估算
3. 當薪資種類為「月薪」：以（月薪 × 12） ÷ （52 × 每週平均工時 - （12天國假 + 7天特休）× 工作日實際工時）估算
4. 當薪資種類為「年薪」：以 年薪 ÷ （52 × 每週平均工時 - （12天國假+7天特休） × 工作日實際工時）估算
```

參考時間的提示字:
`若分享該筆資料的使用者已離職，則參考時間為離職年、月。若尚在職，則為分享資料的年、月。`

![image](https://cloud.githubusercontent.com/assets/3805975/22095237/2f94f464-de4e-11e6-82fb-23d8a1fe0542.png)

p.s. 而且應該是參考時間 (另開issue)

**Comment by wutingy** [comment]
這東西太複雜了，想了良久，決定以 modal 形式處理
