### ISSUE TITLE
以職稱搜尋需顯示公司名稱

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/WorkTimeSurvey#424]
`.search-result-list__heading` 裡面的 `h3`

![screen shot 2017-01-19 at 22 50 05](https://cloud.githubusercontent.com/assets/8353239/22111503/7f31cfa0-de9a-11e6-9e18-24b822e8ace6.png)

**Comment by barry800414** [comment]
是把資料掛進去就可以對嗎?  是的話我可以解
