### ISSUE TITLE
無薪資的資料顯示方式

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#425]
![2017-01-19 10 45 34](https://cloud.githubusercontent.com/assets/7566586/22111515/86cf9ea4-de9a-11e6-843e-950cc6071d0e.png)

沒有薪資的資料，目前是顯示「/」，看要不要改一下

**Comment by wutingy** [comment]
一週總工時、加班頻率、薪資、估計時薪都需要無資料的顯示格式

**Comment by mark86092** [comment]
薪資、估計時薪 的修正可以其他人做

**Comment by wutingy** [comment]
我剛都弄好了～～

**Comment by barry800414** [comment]
@wutingy  想問Tin，薪資、估計時薪的部分，就讓它空白嗎?

**Comment by barry800414** [comment]
阿阿好

**Comment by mark86092** [comment]
動作真快ＸＤ
