### ISSUE TITLE
職稱搜尋的結果顯示

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#428]
![2017-01-19 11 02 58](https://cloud.githubusercontent.com/assets/7566586/22111814/b6437f2e-de9b-11e6-8ee9-76d2a2f54b50.png)

我不知道這算不算issue，但我搜尋職稱看到這樣，搞不懂那兩條結果分別代表什麼？？？（雖然點開知道是不同的職位，但不點開還真不曉得是什麼邏輯）

**Comment by wutingy** [comment]
應該要顯示公司名稱 #424

**Comment by peteranny** [comment]
ok, duplicated
