### ISSUE TITLE
排序欄位上不同顏色

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#431]
單筆資訊的部分，如果以「一週工時」、「估計時薪」排序的時候，highlight那個欄位會不會比較容易發覺是以那個欄位排序?

類似這樣:
![image](https://cloud.githubusercontent.com/assets/3805975/22112177/fbf14118-de9c-11e6-9ab0-12cfcf09ee26.png)

**Comment by mark86092** [comment]
這個有什麼結論嗎？

**Comment by peteranny** [comment]
我附議，我也有這樣想
不過依照網站風格的話感覺會用簡單的 caret 之類的？
不管怎麼標，我都附議要有個標示

**Comment by peteranny** [comment]
不過網站風格的話感覺會用 caret 之類解？
不管怎麼標，我都附議要有個標示

**Comment by wutingy** [comment]
同意在 table 的標題上有箭頭標示

**Comment by mark86092** [comment]
那先交給 @wutingy 處理完再串起來？

**Comment by wutingy** [comment]
ＯＫ！

**Comment by wutingy** [comment]
@barry800414 這邊有個要跟你討論的：

![screen shot 2017-01-21 at 23 41 22](https://cloud.githubusercontent.com/assets/8353239/22175643/151e0368-e034-11e6-99d8-27f13fb9b95f.png)

![screen shot 2017-01-21 at 23 46 12](https://cloud.githubusercontent.com/assets/8353239/22175644/23bfd450-e034-11e6-963d-7c3b0017f4b7.png)

如上兩圖所見，問號會跟箭頭有衝突，我建議保留箭頭，問號按鈕像手機版一樣拉出表格外面，你覺得如何？

![screen shot 2017-01-21 at 23 46 28](https://cloud.githubusercontent.com/assets/8353239/22175654/5308ffa2-e034-11e6-9e52-0757421d36ae.png)

**Comment by wutingy** [comment]
加上 `[data-sort="high"]`  ` [data-sort="low"]` 在 dom 上面即可得到 style。

**Comment by wutingy** [comment]
@mark86092 這個我只做了 style 後來有人串起來了嗎？

**Comment by mark86092** [comment]
有的，在 #456
