### ISSUE TITLE
中視窗的layout

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#432]
![2017-01-19 11 14 41](https://cloud.githubusercontent.com/assets/7566586/22112219/1be3880a-de9d-11e6-8c13-3e657896af87.png)

取中等寬度的視窗時，layout有點醜，看是否要不要更新media-query的條件讓layout好看一點

**Comment by wutingy** [comment]
因為不會有裝置是這個 size 所以不會寫這邊的 rwd
