### ISSUE TITLE
預留loading image空間

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#433]
查詢薪時的頁面拉到最底，會繼續loading，並出現loading image
但是要是沒資料時，頁面又一直往下拉，image就會狂閃 (反覆loading => 沒資料 => loading =>沒資料)
而因為image的高度並沒有預留，所以出現image時會把下面的layout往下擠，而消失時layout又回來
造成image狂閃，下面layout也狂動

想建議預留loading image的空間，讓loading image出現不要造成layout向下擠

**Comment by mark86092** [comment]
想到這個問題當初問什麼沒解了：因為資料有 1000 筆以上，不容易 load 不到資料

不過還是該解掉

**Comment by peteranny** [comment]
就算load到資料，其實也看得出來layout變動得很不尋常
（在before loading和is loading中間也會閃一瞬間layout向下擠）
