### ISSUE TITLE
名稱衝突：資料時間排序 與 資料時間

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#434]
![image](https://cloud.githubusercontent.com/assets/1908007/22112593/79d3809a-de9e-11e6-9ff9-639afe8ff910.png)

這裡：
資料時間排序 --> `created_at`
資料時間 --> `data_time`

**Comment by barry800414** [comment]
下方欄位名稱要改 "參考時間"
而且會有解釋說明參考時間的意義
