### ISSUE TITLE
時間顯示格式建議

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/WorkTimeSurvey#435]
改為 2017.01 會比較好，因為 / 在隔壁是用來當作單位分隔線

![screen shot 2017-01-19 at 23 40 25](https://cloud.githubusercontent.com/assets/8353239/22113366/f9a91706-dea0-11e6-936d-49868eaa7fcf.png)

**Comment by mark86092** [comment]
我也覺得改一下比較好
