### ISSUE TITLE
[資料填寫頁] 填寫數字的表格遇到 "," 的問題

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#440]
isNaN("22,000") => false 但 parseFloat("22,000") => 22 
全部都要做偵測，避免,所產生的問題

目前想的解法是一律要求使用者只能打 nn[.mm] 這樣的格式

包含 #423

**Comment by mark86092** [comment]
#423 ?

**Comment by barry800414** [comment]
包含 #423 ，因為工時那些表格也要處理
