### ISSUE TITLE
表單驗證問題

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/WorkTimeSurvey#441]
薪資 / 工時都不填寫依然可以送出，應為擇一必填。

**Comment by barry800414** [comment]
@xxhomey19

**Comment by barry800414** [comment]
@wutingy 妳說的狀況我試不出來，是用什麼瀏覽器或者填寫了那些欄位?

**Comment by wutingy** [comment]
@barry800414 誒＠＠“ 我也測不出來 應該是誤會了什麼 我先關掉
