### ISSUE TITLE
[表格填寫頁] 上傳按鈕旁的提醒字

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#444]
因為接下來將會規定使用者必須留下一筆資訊或邀請一位朋友留下資訊，才有權限。
可能會讓使用者為了查資訊而亂留資訊。

我在想要不要在上傳按鈕的附近加上:
- [x] 我分享的是真實資訊，並且遵守中華民國法律以及本站[使用者條款](https://worktime.goodjob.life/user-term.html)。
![image](https://cloud.githubusercontent.com/assets/3805975/22171667/dde00506-dfcd-11e6-902d-920cd750ce6a.png)

你們覺得呢?

**Comment by peteranny** [comment]
同意～這還滿重要的@@

**Comment by barry800414** [comment]
![image](https://cloud.githubusercontent.com/assets/3805975/22579125/9eab2c0e-ea08-11e6-92b7-d74c2bc210e8.png)

剛嘗試要去解這個issue，不過看起來還是需要 @wutingy 妳的幫忙QQ
checkbox居然預設不顯示，然後版面也怪怪的

可以麻煩妳style的部分嗎?

**Comment by wutingy** [comment]
mockup 已補上，請善心人士補一下驗證

@xxhomey19 ?

**Comment by mark86092** [comment]
@barry800414 需要傳送資料到後端嗎？

**Comment by barry800414** [comment]
不用
然後前端檢查是不是有打勾的
