### ISSUE TITLE
未達五筆的 style

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/WorkTimeSurvey#453]
![screen shot 2017-01-23 at 22 08 55](https://cloud.githubusercontent.com/assets/8353239/22207059/a00c3906-e1b8-11e6-911d-baa1f69e3161.png)

應該要有個遮罩，不見了

**Comment by mark86092** [comment]
10 天過後我就忘記這個 bug 是描述什麼了

**Comment by wutingy** [comment]
@mark86092 @barry800414 
因為 `g.count == undefined` 所以前端有問題，請問這邊後端吐出來的資料有更動過嗎？

**Comment by mark86092** [comment]
@wutingy 我 check 一下
