### ISSUE TITLE
從低到高的工時排序

### ISSUE THREAD

**Issue by peteranny** [goodjoblife/WorkTimeSurvey#477]
<img width="1183" alt="2017-04-11 4 20 37" src="https://cloud.githubusercontent.com/assets/7566586/24899517/2dc17b92-1ed3-11e7-9ade-fbe666751e3b.png">

若是沒有工時的話應該就不用顯示了？

**Comment by barry800414** [comment]
這應該是個bug

**Comment by mark86092** [comment]
隱藏起來也怪怪的，資料就不見了

**Comment by barry800414** [comment]
我記得這個當時後端討論的結論是，要把沒有平均資訊的放在最後面耶
放在前面真的很怪。

**Comment by mark86092** [comment]
後端我印象討論的是列表那邊，至於 aggregate 的沒討論到

不過這涉及到實作細節，這個aggregate更不好做或高運算，需要仔細思考
