### ISSUE TITLE
隱藏排序後前 1% 的資料

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/WorkTimeSurvey#479]
style 我會再補上～

**Comment by mark86092** [comment]
這個也要麻煩你寫 style 了

**Comment by barry800414** [comment]
這個如果可以的話，希望可以優先做
後端我可以支援

@wutingy 方便估個介面的時程嗎？
@mark86092 想跟你討論細節，我等一下寫在回覆

**Comment by wutingy** [comment]
我這邊，單純 style 的話大概一個晚上可以解決。
我記得當初討論是從前端隱藏就好，不過這看你們～

**Comment by barry800414** [comment]
https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/243

**Comment by wutingy** [comment]
@barry800414  補上設計

https://projects.invisionapp.com/d/main#/console/10208710/249891838/preview
https://projects.invisionapp.com/d/main#/console/10208710/249891837/preview

**Comment by mark86092** [comment]
我拼拼看這幾天能不能做完

**Comment by barry800414** [comment]
@mark86092  這個給我做，你專心 review 前後端的 PR
是我要求 @wutingy  提早出介面的
