### ISSUE TITLE
官網無法登入

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#485]
- [x] mac + safari (ok by Wei-Ming)
- [x] mac + chrome  (ok by Wei-Ming) 
- [x] mac + firefox (ok by Wei-Ming) 
- [ ] windows + IE
- [ ] windows + Firefox
- [x] windows + chrome (win7 無法登入 by Wei-chu)
- [x] iphone + safari (無法登入 by Wei-Ming） 

沒有登入的狀態下，不會出現登入按鈕 (有登入也是一樣）
![17968470_120300003244596036_924978826_o](https://cloud.githubusercontent.com/assets/3805975/25160046/4fba057a-24e6-11e7-8a03-9a3bbf8a19f8.jpg) 
![17968045_120300003283230775_131675087_o](https://cloud.githubusercontent.com/assets/3805975/25160045/4fb29bdc-24e6-11e7-8df7-337485ed4be8.jpg)
![18042746_120300003253365041_1042454796_o](https://cloud.githubusercontent.com/assets/3805975/25160047/4fbbb9d8-24e6-11e7-8855-e194006db81f.jpg)
![18052292_120300003260686940_940002938_o](https://cloud.githubusercontent.com/assets/3805975/25160048/4fbcec90-24e6-11e7-9533-4b66ee44d701.jpg)

iOS version: 10.2.1 (14D27)

- [x] iphone + firefox (ok by Wei-Ming) 
- [x] iphone + chrome (ok by Wei-Ming) 
- [ ] Android + firefox
- [x] Android + chrome (無法登入 by Wei-chu)
- [ ] Android + Native browser

**Comment by wutingy** [comment]
iphone + safari、iphone + chrome 我這邊測試都 ok，版本為`10.3.1`

**Comment by barry800414** [comment]
我有種ＦＢ自己把他玩壞的感覺＝ ＝
我昨天在自己的機器上要build local版的官網，也是類似的問題（登入按鈕不見，或是已經登入也沒用），一直找不到原因，只好放棄先睡。
結果今天秐樟就回報的類似的問題，不過是在手機上的。

**Comment by mark86092** [comment]
下次擬定處理流程，之後有不同的東西要檢查（舉例）：

1. 粉專有沒有人反應
2. developer facebook 有沒有異常(跟平常不同)
3. 系統有沒有異常 (mlab, heroku, redis)

**Comment by mark86092** [comment]
1,2,3 我都看完都沒有
