### ISSUE TITLE
填寫薪水時的輔助字

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#488]
目前想的是放在這個區塊，不過還是由 @wutingy 決定！
![2017-05-01 8 26 33](https://cloud.githubusercontent.com/assets/3805975/25579713/b199fa82-2eac-11e7-874e-03038e9edd5e.png)

輔助字有兩個部分：
1. 輸入薪水時，自動顯示國字的提醒，提醒的單位包含：千、萬、千萬的千。
例如：
`時薪`＋ `2015` -> `時薪 2千15元`
`月薪`＋ `22000` -> `月薪 2萬2千元`
`年薪`＋ `1150000` -> `115萬元`
`年薪`＋ `11110000` -> `1千111萬元`

基本想法是阿拉伯數字的部分不要超過三位，然後因為台灣人習慣用萬，所以還是顯示萬會比較好理解。

2.
大於等於的部分
當使用者選擇 `時薪`，且薪資大於等於 2,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `日薪`，且薪資大於等於 20,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `月薪`，且薪資大於等於 200,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `年薪`，且薪資大於等於 2,000,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”

e.g. `時薪`＋ `2015` -> `時薪 2千15元，確定嗎？` （紅色字）

小於等於的部分
當使用者選擇 `時薪`，且薪資小於 133 的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `日薪`，且薪資小於 500的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `月薪`，且薪資小於 5,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `年薪`，且薪資小於 50,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”

e.g. `月薪` + `3000` -> `月薪 3千，確定嗎？` (紅色字)

**Comment by barry800414** [comment]
目前這是我的提案， @mark86092  @wutingy 麻煩你們看看，有沒有什麼問題或要修改的部分。這個部分我可以寫。

**Comment by mark86092** [comment]
你可以先寫邏輯判斷的部分，

這部分我沒有意見

**Comment by wutingy** [comment]
邏輯上，要不要也判斷小於的？

例如，「月薪小於 19000，確定嗎？」

設計我有空想一下

**Comment by mark86092** [comment]
@barry800414 麻煩回應一下這邊

**Comment by barry800414** [comment]
@wutingy 有道理，我來想想小於的情況怎麼判斷。

**Comment by barry800414** [comment]
小於等於的部分
當使用者選擇 `時薪`，且薪資小於 133 的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `日薪`，且薪資小於 500的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `月薪`，且薪資小於 5,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”
當使用者選擇 `年薪`，且薪資小於 50,000的時候，輔助字變為紅色，並且後綴 “，確定嗎？”

e.g. `月薪` + `3000` -> `月薪 3千，確定嗎？` (紅色字)

這個數字你們看看覺得如何？ 

@wutingy @mark86092

**Comment by wutingy** [comment]
時薪最低不是 133 嗎

**Comment by barry800414** [comment]
改了！

**Comment by wutingy** [comment]
另外，
`年薪` 由最低薪資算，21009*12=252,108，50,000 太少了？
`日新`、`月薪`明顯低於標準，是考量到非正職嗎？

**Comment by mark86092** [comment]
數字的選擇我比較考慮到的是數量級，就是，以年薪來說，數量級應該是 10^5~10^6，而月薪則是 10^4 ~ 10^5

所以如果是要提醒使用者可能把年薪月薪搞混，那年薪的下限可能就要是 100000

**Comment by wutingy** [comment]
我上面在寫啥...數學真的不好...所以彥齊的意思是這樣嗎？
時薪，100
日薪，100
月薪，1,000
年薪，100,000

**Comment by mark86092** [comment]
我的結論是這個沒錯，不過要幾個 0 可以改（例如日薪可以 1000）

我的考量點是使用者可能會犯兩個錯誤：

1. 選錯單位
2. 多打/少打一個位數

所以我才會想大概的範圍就夠應付（粗淺想法）

**Comment by barry800414** [comment]
我覺得這個應該不用很精細，就是避免打錯或選錯而已，而且還是可以上傳的。

時薪估計範圍： 100 ~ 500
日薪估計範圍： 800 ~ 4,000
月薪估計範圍：20,000 ~ 100,000
年薪估計範圍：200,000 ~ 1,000,000

這樣範圍你們覺得OK嗎？
