### ISSUE TITLE
可以填年資卻沒有顯示年資

### ISSUE THREAD

**Issue by bestpika** [goodjoblife/WorkTimeSurvey#496]
在輸入資料的時候有「年資」可以輸入
可是列表顯示卻看不到這個資料
這樣就無法正確反映薪資狀況了
而且這個年資還不是該公司的年資而是「業界工作經歷」
這樣是不是應該也要加入「該公司工作經歷」這個欄位？

**Comment by barry800414** [comment]
![2017-07-01 8 24 52](https://user-images.githubusercontent.com/3805975/27757649-c97d4b4a-5e36-11e7-8b5f-bf3bec3a3b9e.png)

其實是有的！ 但目前放在“搜尋”的結果中才會顯示。
之所以沒有放在“最新薪時”單筆資訊的列表的原因是有點放不下，但我們我們會再討論＆嘗試看看能不能放進去！

另外關於業界工作經歷 v.s. 年資，理想上是兩個都要填寫並且顯示會比較好，但也是考量到填寫的欄位已經夠多，所以當時討論的結論是留下一比較重要的，我們選擇留下業界工作經歷。

**Comment by bestpika** [comment]
我前幾天在用的時候搜尋好像壞了所以看不到
可是業界年資跟工作年資都確實會影響到薪資，光是看其中一種並不能正確反應薪資狀況...
畢竟即使你業界做了 10 年 20 年到了某公司也可能因為制度所以薪水並不是一個這樣經歷的人該有的
特別是那種調薪制度很明確的公司
