### ISSUE TITLE
新網站上線

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/WorkTimeSurvey#497]
- [x] header, footer 要改成與現在一樣
- [x] 填寫頁面只留下填寫區塊就好，route 改成 `/share/time-and-salary`
- [x] 剩下填寫、查詢頁，其他頁面移除（關於、隱私權、使用者等等）

**Comment by wutingy** [comment]
header, footer 可以參考新的 PR https://github.com/goodjoblife/GoodJobShare/pull/175

將原本黃色的 header 改成黑色的

**Comment by wutingy** [comment]
現在 `https://www.goodjob.life` 的填寫頁，要改成 `https://www.goodjob.life/share/time-and-salary`（需要建立新的檔名以符合 route）

該頁面就只有這區塊，其他的刪掉
![screen shot 2017-07-10 at 11 26 56 pm](https://user-images.githubusercontent.com/8353239/28025997-684731ae-65c7-11e7-9d1c-da9f681f83b4.png)

**Comment by mark86092** [comment]
@wutingy 剛好也開了 #498 XD

**Comment by peteranny** [comment]
恩因為我一直沒很清楚WorkTimeSurvey和GoodJobShare是怎麼整合在一起的，只粗略知道後者遇到工時的部分就是連結到前者的static pages，但因為我一直看不懂整合的code在哪裡，所以先確認一下我理解對不對：

原本填工時是放在Landing，然後看工時是另外一頁，所以現在就是要把填工時從Landing拿出來獨立成一頁，然後看工時不動（因為本來就是獨立的一頁），然後針對填工時和看工時這兩頁的header&footer要同步成黑色版本的。是這樣嗎？router的部分，應該不是在這邊做，是要在GoodJobShare那邊做，所以我這邊PR應該是不用管router的部分，是嗎？

**Comment by wutingy** [comment]
@peteranny 
1. 對，要把 landing 獨立成一頁
2. 對，router 部分，是 @mark86092 有針對部署做設定，但你要建一個新的檔案 `time-and-salary.pug`

**Comment by peteranny** [comment]
可是目前「看工時」這一頁的名稱已經是`time-and-salary.pug`了，所以「填工時」就不能取`time-and-alary.pug`了@@ 要怎麼取名好？

**Comment by wutingy** [comment]
@peteranny 歐歐，應該是要建在 `share` 資料夾底下。

**Comment by mark86092** [comment]
@peteranny @wutingy pug 檔案可以不用搬移沒關係，麻煩就直接修改 index.pug 與 time-and-salary.pug 即可

這部分會透過 build 的時候去搬檔案位置，還有 html server 會處理網址

不過麻煩請 merge 進 master 分支～～

**Comment by mark86092** [comment]
See #499 的 build script

**Comment by wutingy** [comment]
喔喔 原來如此！

**Comment by peteranny** [comment]
好的，那我再理解一次：

- `index.pug`刪減成只留填工時
- `time_and_salary.pug`基本上不太需要動

然後兩者的header & footer同步成黑色版本
