### ISSUE TITLE
新網站上線 > header, footer 要改成與現在一樣

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#498]
#497 

目前的 Header 

![image](https://user-images.githubusercontent.com/1908007/28025988-66011d24-65c7-11e7-9150-8d63f001b13f.png)

新版的 Header

![image](https://user-images.githubusercontent.com/1908007/28026029-799f7b00-65c7-11e7-9500-ceac3d51e3d4.png)

**Comment by wutingy** [comment]
header, footer 可以參考新的 PR goodjoblife/GoodJobShare#175

**Comment by mark86092** [comment]
Done
