### ISSUE TITLE
active 顏色不一樣

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#502]
![image](https://user-images.githubusercontent.com/1908007/28629340-b70aa624-7259-11e7-9f7e-71caa76e6df4.png)

![image](https://user-images.githubusercontent.com/1908007/28629362-ca8a5d66-7259-11e7-892f-dc8cd4982c0f.png)

如圖，顏色還需要調整

**Comment by wutingy** [comment]
右邊人頭大小也不一樣，細節我來調整～～

**Comment by wutingy** [comment]
提醒：還有 footer 等到文案確定，這邊要再調一次。

**Comment by mark86092** [comment]
是的，SEO、文案 估計是兩邊要一起調整了
