### ISSUE TITLE
隱藏前 1% 介面優化

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/WorkTimeSurvey#516]
- 修改隱藏文字位置，並加上灰色背景。
- 我想順便把上頭改得整齊一點，後來加了一堆按鈕之後，視線順序變得蠻亂的。

[展開前](https://projects.invisionapp.com/d/main#/console/10208710/251593028/preview)
[展開後](https://projects.invisionapp.com/d/main#/console/10208710/251593027/preview)

再麻煩大家有空看看。

@barry800414 @peteranny @mark86092

**Comment by barry800414** [comment]
@wutingy 我可以先改隱藏 1% 的部分嗎？  
其他文字置左、上方按鈕重新調整的部分，交給妳負責？

**Comment by mark86092** [comment]
看起來不錯

**Comment by wutingy** [comment]
@barry800414 你們覺得 ok 的話，這我可以都做～

**Comment by barry800414** [comment]
介面的部分我覺得沒有問題！

**Comment by peteranny** [comment]
有比較好了~ ok

**Comment by wutingy** [comment]
@peteranny 亭屹～這個 style 修正要麻煩你，因為你已經在移了！感謝，有問題可以問我～

**Comment by peteranny** [comment]
歐歐！好的
