### ISSUE TITLE
表單區(3) 以Facebook登入/開始參與 必須讓使用者能夠 登入

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#56]
送出的流程是：檢查表單 --> fb 登入 --> 送出資料

**Comment by qcl** [comment]
好奇這樣使用者的感覺會是什麼XD

一點猜想：
- 我都已經填這麼多了，只好登入惹
- 靠北要登入耶，算了

**Comment by mark86092** [comment]
這也是個問題

**Comment by mark86092** [comment]
登入的問題討論

**Comment by barry800414** [comment]
確實是個issue ...

**Comment by mark86092** [comment]
後來修的跳出一個 modal 很像也怪怪的xd

**Comment by barry800414** [comment]
這個issue目前還在嗎? 以目前about section會提醒要登入、form section如果沒登入會挑出modal提醒的話

**Comment by mark86092** [comment]
昨天@qcl 有提到 表單區的 modal 跳出來一下下又關掉會不會很怪？

**Comment by barry800414** [comment]
是指登入後，modal跳出來一下下又消失嗎?

**Comment by mark86092** [comment]
未登入者：表單區 --> 按下 submit --> 跳出 modal --> 登入 --> modal 消失

See #111
