### ISSUE TITLE
感謝參與並分享區(4) 分享按鈕，分享這個網頁

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#58]
![image](https://cloud.githubusercontent.com/assets/1908007/16545724/58826ed6-4166-11e6-89ba-2a263891f113.png)

**Comment by barry800414** [comment]
這邊會改掉

**Comment by mark86092** [comment]
會改掉什麼？

**Comment by barry800414** [comment]
![_000](https://cloud.githubusercontent.com/assets/3805975/16545961/a7389fea-416c-11e6-8edd-a45d9afb4818.jpeg)

**Comment by mark86092** [comment]
修正：這個 issue 非關頁面，只是分享按鈕按下去沒反應而已

**Comment by mark86092** [comment]
Fix by #82
