### ISSUE TITLE
文案修正

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#59]
《第一頁》
title:工時透明化運動
Subtitle: 分享你的真實工時資訊，讓我們一起改善工時不透明的現況！

《第二頁》
你是否和我們有一樣的經驗？

在求職網站上看到的上下班時間總是只寫著「日班」或「依公司規定」；面試時談的工作時間和實際上的總是不同。如果一開始就能知道真正的工時，我們是不是可以做出更好的選擇？

「工時透明化運動」希望藉由每個人分享最近一週的實際工時，讓不同公司、不同職位的工時能夠更公開透明。而留下資訊後，你將可以查詢所有其他人分享的資訊。

我們誠摯地邀請你，一起改善工時不透明的現況！

**Comment by mark86092** [comment]
第二頁文案超長的耶，iphone 5 的寬度來看，這裡 2 行會變 5~6 行
