### ISSUE TITLE
Landing Page 整體概觀

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#61]
[畫面配置&文案 20160704.pdf](https://github.com/goodjoblife/WorkTimeSurvey/files/347019/20160704.pdf)

這裡有記錄，我覺得差不多了
只是表格&感謝參與分享區，我想說拆成兩個好了?

By @barry800414 
- [ ] Section1. 主視覺
  - [x] #65
- [ ] Section2-1 介紹文案區
- [ ] Section2-2 介紹文案區
- [ ] Section3. 表單區（填寫）
  - [x] #56 
  - [x] #67
- [x] Section4. 感謝參與並分享區
- [x] Section5. Q&A 區
- [x] Section6. 聯絡我們

**Comment by barry800414** [comment]
https://docs.google.com/document/d/1eTbE8SrPeAwafqTkXSCYFuolb0O1li33wafZDfSnuas/edit?usp=sharing

這裡有記錄，我覺得差不多了
只是表格&感謝參與分享區，我想說拆成兩個好了?

- [ ] Section1. 主視覺
- [ ] Section2.介紹文案區
- [ ] Section3.表單區（填寫）
- [ ] Section4. 感謝參與並分享區
- [ ] Section5. Q&A 區
- [ ] Section6. 聯絡我們

**Comment by barry800414** [comment]
畫面配置&流程更新
 Section1. 主視覺  (一個button往下滑)
 Section2. 介紹文案區 (一個button -> fb-login，help-text->modal)
 Section3. 表單區（填寫） if(not login) {button -> modal -> fb-login -> submit} else { button -> submit }
 Section4. 感謝參與並分享區
 Section5. Q&A 區
 Section6. 聯絡我們
