### ISSUE TITLE
主視覺區(1) 的導航按鈕

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#68]
按下去之後有開始填表 與 了解更多

**Comment by barry800414** [comment]
我按鈕的class設定是這樣: col-sm-4 col-sm-offset-1 col-xs-10 col-xs-offset-1
原因是，我希望螢幕足夠大(平板及以上)的時候，可以左右排，螢幕很小的時候(手機)，上下排，才不會太擠。有更好的方法請提供。
