### ISSUE TITLE
show_workings.js 預設就會讀取

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#85]
#84: 在感謝與分享(結果)的section插入最新N筆資料的表。

問題1. show_workings.js預設就會去讀取資料，但我們要的應該是使用者留完資料才去讀取。
可以不要預設會讀取嗎?

問題2. 沒辦法選擇要取得最新N筆的N，需要多一個參數。
此外，此issue與 #70 相關。

**Comment by mark86092** [comment]
的確是 show_working.js 的關係，到時候來想想怎麼拆開
