### ISSUE TITLE
介紹區(2) 文案拆為兩段

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/WorkTimeSurvey#92]
according to #61, 介紹區的文案會拆成兩段，原因是段落太長

第一個section: 文字介紹+ 往下的圓形按鈕
第二個section: 文字介紹+ 兩個按鈕(開始參與+分享)

This issue is also related to  #66

**Comment by barry800414** [comment]
#94

**Comment by mark86092** [comment]
Done
