### ISSUE TITLE
[Proposal] Refactoring grascale.js

### ISSUE THREAD

**Issue by mark86092** [goodjoblife/WorkTimeSurvey#93]
`grascale.js` 是布景專用的js，但目前由多個頁面共用

所以我想要把上面的 code 分開，首頁用的 js function 如果非要共用，可以考慮直接寫在 html 中

主要是想避免 `grascale.js` 上面的額外 code 影響到其他頁（例如送表單的 event callback 就不該出現在 show.html）

徵詢看看大家，這件事情不急

**Comment by mark86092** [comment]
See #104

**Comment by barry800414** [comment]
很合理，感覺是共用的再寫到grayscale.js裡面就好
